### ISSUE TITLE
Unable to copy files into RUNDIR via shell_commands

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#1792] opened 2017-08-04 16:55 UTC
In setting up a compset, I was trying to copy a couple of files into the RUNDIR by placing the cp commands in the shell_commands file in the usermods_dirs subdirectory (the only way I could see to do this with the existing tools)

Using the --debug setting on create_newcase, I see that shell_commands is run by create_newcase and this is before the run directory is created by case.setup.   The variable RUNDIR is set to the proper value when shell_commands is run, but the directory does not exist. 

I can see a couple of possible solutions;
1) Add a directory similar to SourceMods (maybe RunMods) which contains the files which are copied into the run directory.
2) Add a setup_commands file which is run similar to shell_commands but runs at the case.setup stage.

My workaround for now (and if a better solution is not implemented) is to do my own mkdir to create the RUNDIR inside shell_commands before issuing the cp commands.  This feels dangerous since case.setup will be attempting to mkdir this same directory, but for now, this seems to work.

**Comment by jedwards4b** [comment] 2017-08-04 17:06
case.setup is already capable of handling a run directory that already exists so no problem creating it with a shell_command.   From our offline conversation I think that the real problem is that the mechanism for staging a hybrid or branch run is somehow broken - I think that would be a better issue to open.

**Comment by jedwards4b** [comment] 2017-08-04 18:35
The problem is that check_input_data is called by case.submit but the pop buildnml expects the rpointer file to be in the run directory when preview_namelists is run.   I think that we need to add a call to check_input_data in the preview_namelist script if get_refcase is true.

**Comment by billsacks** [comment] 2017-08-10 18:37
@cacraigucar and @jedwards4b : it sounds like the underlying problem that motivated this use case has been resolved. Should we close this issue? While I see Cheryl's point in theory, my feeling is that, if there are no outstanding use cases that require this feature, then it's not worth adding the extra complexity.

**Comment by jedwards4b** [comment] 2017-08-10 18:49
This should have been closed by PR#1795

**Closed by jedwards4b** 2017-08-10 18:49 UTC
Labels: ty: enhancement
