### ISSUE TITLE
mpi-serial not working on anlworkstation

### ISSUE THREAD

**Issue by sarich** [ESMCI/cime#667] opened 2016-10-12 16:37 UTC
Using mpi-serial, the netcdf library has an unresolved depency on MPI_File_open

**Comment by jayeshkrishna** [comment] 2017-01-20 18:20
This fell off my radar. I will try a build on anlworkstation with mpi-serial to reproduce this issue.

**Comment by jayeshkrishna** [comment] 2017-01-20 18:51
So apparently the issue is that the wrong netcdf library is included for anlworkstation in the mpi-serial case.
Currently parallel versions of hdf5 and netcdf are loaded for all mpilibs (including mpi-serial). If the serial version of netcdf library (and no hdf5 required here) is included for mpi-serial builds the build completes successfully. The parallel versions of netcdf library require mpi_file_open() but serial versions do not.
I will create a PR soon.

**Comment by jayeshkrishna** [comment] 2017-01-20 18:53
Unfortunately we don't have the soft env key for the netcdf serial libs. I will ping systems about it.

**Comment by jayeshkrishna** [comment] 2017-01-20 20:22
This issue will be fixed after resolving Issue #1033 (a separate issue that needs to be fixed for building CIME on compute001)

**Comment by jayeshkrishna** [comment] 2017-01-20 22:11
The soft key +netcdf-4.4.1c-4.2cxx-4.4.4f-serial-gcc6.2.0 is now available on compute001 .

**Comment by rljacob** [comment] 2017-05-06 02:52
Was this fixed?

**Comment by jayeshkrishna** [comment] 2017-05-08 16:34
No, this was kept on hold due to the recent CIME merge (reorganization of the source tree etc). I will fix this on the ACME side today.

**Comment by jayeshkrishna** [comment] 2017-05-09 18:22
This ACME-specific issue is being handled in ACME-Climate/ACME#1504 . Should be brought in to ESMCI/cime in the next ACME->CIME sync.

**Closed by jayeshkrishna** 2017-05-09 18:22 UTC
Labels: bug, in progress, machine files
