### ISSUE TITLE
DOCN%SOMAQP producing NaN values at f09_g17

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1801] opened 2017-08-09 19:08 UTC
It's trying to pass NaN values through the coupler which are correctly being detected by check_fields which causes an abort.    This is happening in the alpha07c candidate which is available from https://svn-ccsm-models.cgd.ucar.edu/cesm2/alpha/branches/cesm2_0_alpha07

Since this is a component independent cime test it can probably be reproduced on the current cime trunk.

**Comment by jedwards4b** [comment] 2017-08-09 19:16
I have confirmed that this problem is reproducible from the current cime master.

**Comment by gold2718** [comment] 2017-08-09 23:22
I think this issue is mislabeled. I note that the following test also fails the same way:
`SMS.f09_g17.2000_DATM%NYF_SLND_SICE_DOCN%SOMAQP_SROF_SGLC_SWAV.hobart_nag.drv-som`
while
`SMS.f09_g17.2000_DATM%NYF_SLND_SICE_DOCN%DOM_SROF_SGLC_SWAV.hobart_nag.drv-som`
passes. Neither test uses `PRE` or any `ESP` code.
@jedwards, if you agree, please reassign and rename the issue title.

**Comment by mvertens** [comment] 2017-08-16 02:59
The right test to run for stand-alone CIME is 

`SMS.f09_f09_mg17.2000_DATM%NYF_SLND_SICE_DOCNOMAQP_SROF_SGLC_SWAV.yellowstone_intel`
   not 
`SMS.f09_g17.2000_DATM%NYF_SLND_SICE_DOCNOMAQP_SROF_SGLC_SWAV.yellowstone_intel`

When you run f09_g17 - the domain is g17 rather than f09 - and even though the mask is set to 1 after ggrid is determined - remapping seems to introduce the mask back into the output I believe. We have never tested this type of configuration and if we had run this with cam - the model would have blown up independent of the new nan check in the driver.

@fischer-ncar - I am reassigning this issue to you in order for you to change the test in CIME to the above. I have verified that running this works out of the box with the above test.
You also need to remove the drv_som from the test name for this case. With the drv_som suffix - things will not work since it hard-wires the following:
`DOCN_SOM_FILENAME="pop_frc.1x1d.090130.nc"`
which is incorrect for this aquaplanet som case.

**Comment by jedwards4b** [comment] 2017-08-16 13:44
Should be DOCN%SOMAQP?

**Comment by fischer-ncar** [comment] 2017-08-16 15:30
Should I also fix the ADESP test grid in  scripts/lib/update_acme_tests.py
```
                               "PRE.f19_f19.ADESP",
                               "PRE.f19_f19.ADESP_TEST")
```

**Comment by gold2718** [comment] 2017-08-16 15:44
I'm not sure f19_f19 has the same problem as f09_g17 but it is important to note that ACME does not have grids such as f09_f09_mg17 (they don't have any of the mask aliases such as *_mg16 or *_mg17).

**Comment by jedwards4b** [comment] 2017-08-16 15:46
Specifying a grid mask at all - mg16 or mg17 doesn't make any sense for an aquaplanet.

**Comment by gold2718** [comment] 2017-08-16 16:29
> Specifying a grid mask at all - mg16 or mg17 doesn't make any sense for an aquaplanet.

Right but the issue is that f09_g17 requires mapping and that is exposing some underlying issue. f19_f19 does not require mapping (so no mask is required). f09_f09 is also okay.

**Comment by jedwards4b** [comment] 2017-08-16 16:36
@mvertens said "The right test to run for stand-alone CIME is

SMS.f09_f09_mg17.2000_DATM%NYF_SLND_SICE_DOCNOMAQP_SROF_SGLC_SWAV.yellowstone_intel"    I disagree - it should be f09_f09 and no mask should be required.

**Comment by fischer-ncar** [comment] 2017-08-16 16:46
I also found a f19_f19_mg17 DOCN%SOMAQP test.   I'll remove that mask, along with the other f09 masks for DOCN%SOMAQP tests.

**Comment by gold2718** [comment] 2017-08-16 16:49
I believe that f09_f09 is okay. Changing the PRE test to use that grid solves the immediate problem but not the underlying issue of what to do with grids such as f09_g17.

**Comment by jedwards4b** [comment] 2017-08-16 16:50
One solution might be to throw an error if any docn aquaplanet compset is attempted with those grids.

**Closed** 2017-08-16 19:26 UTC
