### ISSUE TITLE
Possible problem with required_gridmap setting

### ISSUE THREAD

**Issue by jonbob** [ESMCI/cime#3254] opened 2019-10-01 16:34 UTC
We've run into an issue with an E3SM PR where we've added code to try to make ATM2ROF maps required for compsets with active MOSART, but that functionality doesn't appear to be working because all configurations end up looking for those maps, regardless of ROF model. I have added a CIME branch that I think should demonstrate the problem:
[cime/test-required_gridmap](https://github.com/ESMCI/cime/tree/jonbob/cime/test-required_gridmap)

**Comment by jedwards4b** [comment] 2019-10-01 19:23
@jonbob I just pushed a fix to your branch, can you try it before I open a PR?

**Comment by jonbob** [comment] 2019-10-01 19:24
Sure -- thanks

**Comment by jonbob** [comment] 2019-10-01 19:38
I got this?
````./create_test SMS.T62_oQU240.CMPASO-NYF.anvil_intel
Using project from env PROJECT: condo
Creating test directory /lcrc/group/acme/jwolfe/acme_scratch/anvil/SMS.T62_oQU240.CMPASO-NYF.anvil_intel.20191001_143436_r326i7
RUNNING TESTS:
  SMS.T62_oQU240.CMPASO-NYF.anvil_intel
Starting CREATE_NEWCASE for test SMS.T62_oQU240.CMPASO-NYF.anvil_intel with 1 procs
Finished CREATE_NEWCASE for test SMS.T62_oQU240.CMPASO-NYF.anvil_intel in 1.883523 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /lcrc/group/acme/jwolfe/acme_scratch/anvil/SMS.T62_oQU240.CMPASO-NYF.anvil_intel.20191001_143436_r326i7
    Errors were:
        Traceback (most recent call last):
          File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/create_newcase", line 227, in <module>
            _main_func(__doc__)
          File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/create_newcase", line 222, in _main_func
            input_dir=input_dir, driver=driver, workflow_case=workflow, non_local=non_local)
          File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 1603, in create
            workflow_case=workflow_case, non_local=non_local)
          File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 918, in configure
            gridinfo = grids.get_grid_info(name=grid_name, compset=self._compsetname, driver=driver)
          File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/Tools/../../scripts/lib/CIME/XML/grids.py", line 73, in get_grid_info
            gridmaps = self._get_gridmaps(component_grids, driver, compset)
          File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/Tools/../../scripts/lib/CIME/XML/grids.py", line 339, in _get_gridmaps
            map_ = gridmaps[self.text(node)]
        KeyError: 'ATM2ROF_SMAPNAME'
````

**Comment by jedwards4b** [comment] 2019-10-01 19:41
Did you change it from ATM2ROF_FMAPNAME to ATM2ROF_SMAPNAME?   Did you provide an actual mapping file?   That wasn't in your branch.

**Comment by jedwards4b** [comment] 2019-10-01 19:44
What I fixed is that you can now specify a required_grid based on compset - now you need to actually define that grid.

**Comment by jonbob** [comment] 2019-10-01 20:12
Those gridmaps are defined, but only for compsets that require them. And sorry, I had both ATM2ROF_FMAPNAME and ATM2ROF_SMAPNAME in the branch I'm really trying to work on. I removed the SMAP part in config_grids and now get
````
[jwolfe@b512 scripts]$ ./create_test SMS.T62_oQU240.CMPASO-NYF.anvil_intel
Using project from env PROJECT: condo
Creating test directory /lcrc/group/acme/jwolfe/acme_scratch/anvil/SMS.T62_oQU240.CMPASO-NYF.anvil_intel.20191001_150932_46na9n
RUNNING TESTS:
  SMS.T62_oQU240.CMPASO-NYF.anvil_intel
Starting CREATE_NEWCASE for test SMS.T62_oQU240.CMPASO-NYF.anvil_intel with 1 procs
Finished CREATE_NEWCASE for test SMS.T62_oQU240.CMPASO-NYF.anvil_intel in 3.470358 seconds (PASS)
Starting XML for test SMS.T62_oQU240.CMPASO-NYF.anvil_intel with 1 procs
Finished XML for test SMS.T62_oQU240.CMPASO-NYF.anvil_intel in 0.281848 seconds (PASS)
Starting SETUP for test SMS.T62_oQU240.CMPASO-NYF.anvil_intel with 1 procs
Finished SETUP for test SMS.T62_oQU240.CMPASO-NYF.anvil_intel in 4.142686 seconds (FAIL). [COMPLETED 1 of 1]
    Case dir: /lcrc/group/acme/jwolfe/acme_scratch/anvil/SMS.T62_oQU240.CMPASO-NYF.anvil_intel.20191001_150932_46na9n
    Errors were:
        /lcrc/group/acme/jwolfe/acme_scratch/anvil/SMS.T62_oQU240.CMPASO-NYF.anvil_intel.20191001_150932_46na9n/env_mach_specific.xml already exists, delete to replace
        /lcrc/group/acme/jwolfe/acme_scratch/anvil/SMS.T62_oQU240.CMPASO-NYF.anvil_intel.20191001_150932_46na9n/env_mach_specific.xml already exists, delete to replace
        WARNING: Should be running with salinity restoring on!
                 But no file available for this grid.
        ERROR: Need to provide valid mapping file between atm and rof in xml variable atm2rof_fmapname
````

**Comment by jonbob** [comment] 2019-10-01 20:18
So the tests I'm running first are from a compset that does not have MOSART -- and therefore should not require these new mapping files

**Comment by jedwards4b** [comment] 2019-10-01 20:57
What is the compset long name for CMPASO-NYF?

**Comment by jonbob** [comment] 2019-10-01 20:59
```<lname>2000_DATM%NYF_SLND_DICE%SSMI_MPASO%DATMFORCED_DROF%NYF_SGLC_SWAV</lname>```

**Comment by rljacob** [comment] 2019-10-01 20:59
2000_DATM%NYF_SLND_DICE%SSMI_MPASO%DATMFORCED_DROF%NYF_SGLC_SWAV_SIAC_SESP

**Comment by jedwards4b** [comment] 2019-10-01 21:24
Can you add a line at 300 of grids.py:

print("gridmaps = {}".format(gridmaps))

**Comment by jonbob** [comment] 2019-10-01 21:35
Sure -- give me a minute to rerun it

**Comment by jonbob** [comment] 2019-10-01 21:41
Seems like it didn't print anything? Does that make sense? Here's what the grids.py looks like:
````
    def _get_gridmaps(self, component_grids, driver, compset):
        """
        set all mapping files for config_grids.xml v2 schema
        """
        grids = [("atm_grid","a%"), ("lnd_grid","l%"), ("ocn_grid","o%"), \
                 ("rof_grid","r%"), ("glc_grid","g%"), ("wav_grid","w%"), ("iac_grid","z%")]
        gridmaps = {}

        # (1) set all possibly required gridmaps to idmap
        required_gridmaps_node = self.get_child("required_gridmaps")
        required_gridmap_nodes = self.get_children("required_gridmap", root=required_gridmaps_node)

        for node in required_gridmap_nodes:
            compset_att = self.get(node,"compset")
            not_compset_att = self.get(node,"not_compset")
            if compset_att and not compset_att in compset or \
               not_compset_att and not_compset_att in compset:
                required_gridmap_nodes.remove(node)
                continue
            gridmaps[self.text(node)] = "idmap"

        print("gridmaps = {}".format(gridmaps))

````
But no output from create_test with gridmaps

**Comment by jedwards4b** [comment] 2019-10-01 21:42
I think you'll find the output in TestStatus.log - or you can just run create_newcase instead.

**Comment by jonbob** [comment] 2019-10-01 21:45
OK, thanks:
````
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'ROF2OCN_LIQ_RMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'OCN2WAV_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'LND2ROF_FMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'ROF2LND_FMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'ICE2WAV_SMAPNAME': 'idmap', 'ROF2OCN_ICE_RMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
````

**Comment by jedwards4b** [comment] 2019-10-01 22:19
That code is working as expected, the problem is now in mct buildnml but I haven't been able to reproduce it.

**Comment by jonbob** [comment] 2019-10-02 15:12
I changed the ATM2ROF maps to be idmap_ignore by default in the mct config_component.xml and it seems to be working now? Does that make sense to you?

**Comment by jedwards4b** [comment] 2019-10-02 15:18
Yes! That makes sense.  Great... do you want me to submit this as a PR or do you just want to include it in yours?

**Comment by jonbob** [comment] 2019-10-02 15:23
I can include it in mine, since it seems to be a separate process to get CIME changes merged between E3SM and CESM. Can you help me know if we need the modifications to grid.py? I'll remove the print statement, but is the rest of it required?

**Comment by jedwards4b** [comment] 2019-10-02 15:26
Yes the rest is required.  Just remove the print.  Thanks

**Closed by jedwards4b** 2019-10-02 15:26 UTC

**Comment by jonbob** [comment] 2019-10-02 15:30
OK -- and thanks for all your help!

**Comment by jonbob** [comment] 2019-10-02 18:02
@jedwards4b - any reason this would fail for ATM2ROF_SMAPNAME? I put this fix back into the code I was trying to merge and it works for ATM2ROF_FMAPNAME but fails when ATM2ROF_SMAPNAME is included...

**Comment by jedwards4b** [comment] 2019-10-02 18:06
They should be treated the same way - do you have the same changes for both variables?

**Comment by jonbob** [comment] 2019-10-02 19:01
I thought I did -- and grepping certainly makes it look like it. I'll add the print line back and post the output?

**Comment by jonbob** [comment] 2019-10-02 19:08
````
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2WAV_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'OCN2WAV_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2WAV_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'OCN2WAV_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2WAV_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'ICE2WAV_SMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'ROF2OCN_LIQ_RMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'OCN2WAV_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2WAV_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'ICE2WAV_SMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'ROF2OCN_LIQ_RMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'OCN2WAV_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'ATM2WAV_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'ICE2WAV_SMAPNAME': 'idmap', 'ROF2OCN_ICE_RMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'ROF2OCN_LIQ_RMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'OCN2WAV_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'LND2ROF_FMAPNAME': 'idmap', 'ATM2WAV_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'ICE2WAV_SMAPNAME': 'idmap', 'ROF2OCN_ICE_RMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
gridmaps = {'ATM2OCN_FMAPNAME': 'idmap', 'ATM2LND_SMAPNAME': 'idmap', 'ROF2OCN_LIQ_RMAPNAME': 'idmap', 'LND2ATM_SMAPNAME': 'idmap', 'OCN2WAV_SMAPNAME': 'idmap', 'ATM2OCN_SMAPNAME': 'idmap', 'LND2ROF_FMAPNAME': 'idmap', 'ATM2WAV_SMAPNAME': 'idmap', 'ATM2OCN_VMAPNAME': 'idmap', 'ROF2LND_FMAPNAME': 'idmap', 'LND2ATM_FMAPNAME': 'idmap', 'ICE2WAV_SMAPNAME': 'idmap', 'ROF2OCN_ICE_RMAPNAME': 'idmap', 'OCN2ATM_FMAPNAME': 'idmap', 'ATM2LND_FMAPNAME': 'idmap', 'OCN2ATM_SMAPNAME': 'idmap'}
Traceback (most recent call last):
  File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/create_newcase", line 227, in <module>
    _main_func(__doc__)
  File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/create_newcase", line 222, in _main_func
    input_dir=input_dir, driver=driver, workflow_case=workflow, non_local=non_local)
  File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 1603, in create
    workflow_case=workflow_case, non_local=non_local)
  File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/Tools/../../scripts/lib/CIME/case/case.py", line 918, in configure
    gridinfo = grids.get_grid_info(name=grid_name, compset=self._compsetname, driver=driver)
  File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/Tools/../../scripts/lib/CIME/XML/grids.py", line 73, in get_grid_info
    gridmaps = self._get_gridmaps(component_grids, driver, compset)
  File "/blues/gpfs/home/jwolfe/e3sm_commit2/cime/scripts/Tools/../../scripts/lib/CIME/XML/grids.py", line 342, in _get_gridmaps
    map_ = gridmaps[self.text(node)]
KeyError: 'ATM2ROF_SMAPNAME'

````
??

**Comment by jedwards4b** [comment] 2019-10-02 19:20
KeyError suggests that you didn't add the variable in src/drivers/mct/cime_config/config_component.xml 
you will also need to add it to the namelist_definition_drv.xml file

**Comment by jonbob** [comment] 2019-10-02 19:20
It seems to be a problem with having two of these gridmaps required based on a compset. I switched the order in config_grids and it always complains about the second map. I can leave either of them in and it's fine, but not both

**Comment by jedwards4b** [comment] 2019-10-02 19:23
I see the problem - I made a change but forgot to give it to you.  Hang on a moment.

**Comment by jonbob** [comment] 2019-10-02 19:25
Both of those maps are in those two xml files, so it must be something about being the second record?

**Comment by jonbob** [comment] 2019-10-02 19:25
oh good, thanks!

**Comment by jedwards4b** [comment] 2019-10-02 19:25
at line 290 of grids.py do:
-
-        for node in required_gridmap_nodes:
+        tmp_gridmap_nodes = required_gridmap_nodes
+        for node in tmp_gridmap_nodes:
