### ISSUE TITLE
make a common driver config_component.xml file

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#3997] opened 2021-06-10 19:52 UTC
https://github.com/ESCOMP/CMEPS/issues/203

**Comment by rljacob** [comment] 2021-06-10 21:33
Is all discussion supposed to go to ESCOMP/CMEPS#203 ?

**Comment by jedwards4b** [comment] 2021-06-10 21:45
No, I think that we can have the discussion here.  I will add a note there referring to this issue.

**Comment by rljacob** [comment] 2021-06-10 21:47
ok reposting:  When we added "CASE_HASH", that's not really part of the driver but it had to be in mct-driver/cime_config/config_component.xml for it be listed in case_env.xml.  cc @jasonb5

**Comment by billsacks** [comment] 2021-06-11 02:54
This is a duplicate of #3509 - see that issue for some additional discussion.

**Comment by billsacks** [comment] 2021-06-11 02:54
@jedwards4b @rljacob can we close this one and just keep the pre-existing #3509 ?

**Comment by rljacob** [comment] 2021-06-11 03:12
fine with me.

**Closed** 2021-06-11 13:34 UTC
