### ISSUE TITLE
Are CIME testing instructions up to date?

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#349] opened 2016-08-07 19:29 UTC
I am trying to follow the [testing instructions](https://github.com/ESMCI/cime/wiki/Testing) on the CIME wiki  and can't get them to work. Can someone help me figure out if there is a bug in master or if it is a PBCAK?
First, I tried the instruction as outlined in the first code box (everything from a Yellowstone login node):
`module load python; ./scripts_regression_tests --fast`
On master (cime5.0.5), I got 7 errors, is this correct? If not, what is wrong? The output is at https://gist.github.com/gold2718/a6791f61aa083713ccba4ad0f4250d6d
BTW, I note that, since I did not define CIME_MODEL, it guessed ACME. With an explicit CIME_MODEL=cesm, I get 3 failures. Gist at: https://gist.github.com/gold2718/f7642400bbb0e35051f26fcfabdffa56

The current open pull requests do not mention test failures and some say the answers are bit-for-bit. So is something wrong with how I am running the tests or is master broken or are those FAILures okay with everyone?

**Comment by jgfouca** [comment] 2016-08-07 20:56
@gold2718 our CIME dashboard is here: http://my.cdash.org/index.php?project=CIME
As you can see, we aren't 100% clean, but we're very close. You should not be seeing 7 failures. @jedwards4b may be able to help out here, I don't have an account on yellowstone.

**Comment by gold2718** [comment] 2016-08-07 22:16
Hmm. According to that, the tests passed on Caldera (part of the Yellowstone cluster where we run jobs like this). From that page, how to I tell what tag and test command was used?

**Comment by jedwards4b** [comment] 2016-08-08 15:46
The nightly tests happen from the HEAD of esmci master.    I have updated the testing instructions with notes regarding yellowstone testing.

**Comment by rljacob** [comment] 2016-08-08 17:16
@jgfouca can you add the hash tested to the "OS version" line as is done for the ACME dashboard?

**Comment by jgfouca** [comment] 2016-08-08 18:56
@rljacob I was able to do that on the ACME side because we aren't actually using CTest. We make the ctest-compatible XML ourselves and therefore have full control. I'm not sure how to do that through CTest, but I can investigate.

**Comment by rljacob** [comment] 2016-08-09 03:45
In that case, do we know what time it does the checkout of  master?  Also is it running ./scripts_regression_tests with or without "--fast"?

**Comment by jedwards4b** [comment] 2016-08-09 13:06
Are we talkng about yellowstone or something else?   On yellowstone it runs at 5am and does not use the --fast option.

**Comment by rljacob** [comment] 2016-08-09 14:18
I didn't think it was a different command for each machine so asking for both of them.

**Comment by jgfouca** [comment] 2016-08-09 16:01
@rljacob both melvin and skybridge start in the middle of the night, they do not use --fast because we want to be sure to run cime_developer.

**Comment by rljacob** [comment] 2016-08-09 17:03
How about this for a new recommended by-hand test procedure:
if your branch changes python and Fortran:  run scripts_regression_tests
If your branch just changes python:  run scripts_regression_tests --fast
If you branch just changes Fortran:  run create_test cime_developer.

Since we don't have a next branch, everyone has to do by-hand testing before issuing the PR.

**Comment by jgfouca** [comment] 2016-08-09 17:05
@rljacob : python changes alone could very easily break 'create_test cime_developer'. I do agree with you that if you only make fortran changes, you don't need to run scripts_regression_tests.

**Comment by rljacob** [comment] 2016-08-10 16:26
If you're on a machine without a batch system, you have to use --no-batch ?   BTW, scripts_regression_tests doesn't have a --help option.

**Comment by jedwards4b** [comment] 2016-08-10 16:43
No, if the config_machines.xml has batch_system=none then you should not need the --no-batch flag

**Comment by billsacks** [comment] 2016-08-16 01:48
Can somebody please clarify the conclusions of this discussion? The instructions here https://github.com/ESMCI/cime/wiki/Testing say to run scripts_regression_tests with --fast, but it seems like some people are saying that you should _not_ use --fast?

Also, it would help me if someone explained the relationship between scripts_regression_tests with/without --fast and `create_test cime_developer`. Is running scripts_regression_tests without --fast the same as running:
```
./scripts_regression_tests --fast
./create_test cime_developer
```
?  If so, are any failures in the cime_developer test suite reported in the output from scripts_regression_tests? And where can I find these system tests (e.g., CASE directories) if I want to see more details?

It would help me if this were all explained here https://github.com/ESMCI/cime/wiki/Testing

**Comment by jedwards4b** [comment] 2016-08-16 01:53
Yes, running scripts_regression_tests without --fast is the same as with fast plus cime_developer.
The default for create_test is to create the case directory as the root of bld and run directories
on yellowstone this is in /glade/scratch/user/$CASE

I do not use fast on yellowstone, I do execca ./scripts_regression_tests  - I've tried to set it up so that the shortest tests run first and the longest are at the end - my rational is that if its failing the short tests you can kill it and fix those before you bother with the longer tests.   The list of cime_developer tests is defined in cime/utils/python/update_acme_tests.py

**Comment by billsacks** [comment] 2016-08-16 12:50
Also, I just ran scripts_regression_tests from the latest master and got one failure:

```
======================================================================
FAIL: test_b_full (__main__.E_TestTestScheduler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 601, in test_b_full
    "Broken test did not report build error")
AssertionError: Broken test did not report build error
```

despite all tests being listed as passing on cdash (if I'm interpreting it right). Is this expected?

**Comment by jedwards4b** [comment] 2016-08-16 13:30
See my note on slack - the test seems to be behaving properly, this appears to be a problem in scripts_regression_tests.   Not expected.

**Comment by jedwards4b** [comment] 2016-08-16 13:31
GIven that the test is sometimes passing and sometimes failing I think we have a race condition in wait_for_tests.

**Comment by billsacks** [comment] 2016-08-16 18:41
I have taken a stab at updating the instructions here https://github.com/ESMCI/cime/wiki/Testing based on the input given above. If others are happy with that, then I would propose that we close this issue.

**Closed** 2016-10-07 18:08 UTC
