### ISSUE TITLE
Adding absolute path to ice_ic options, 'none' and 'default'

### ISSUE THREAD

**Issue by dabail10** [ESMCI/cime#2993] opened 2019-02-04 23:23 UTC
I believe this might have come in under #964, but I'm not sure. Basically, the ice_ic option in user_nl_cice either takes a file name with absolute path or the options 'none' or 'default'. This worked in  earlier tags. Not sure what changed here.

**Comment by jedwards4b** [comment] 2019-02-04 23:42
I'm not understanding this - what does it take to produce an error and what is the expected result?

**Comment by mvertens** [comment] 2019-02-04 23:45
Here is my understanding: If you change user_nl_cice to have ice_ic =
'default' or ice_ic = 'none', it is prepending the inputdata root in front
of it in the inputdata list.

**Comment by jedwards4b** [comment] 2019-02-04 23:51
I tested both ice_ic ='default' and ice_ic = 'none' in maint-5.6 and it works fine.
However it is broken on cime master, I will fix.

**Comment by mvertens** [comment] 2019-02-04 23:54
@jedwards4b - thank you so much for your quick response in helping. I'm
really glad its not broken on cime master.

**Comment by jedwards4b** [comment] 2019-02-05 01:03
@dabail10  The fix is in the cice trunk buildnml - I cannot reproduce the problem in the release.
I checked out a new copy of the release just to make sure and confirmed that I cannot reproduce on the release.

**Comment by dabail10** [comment] 2019-02-05 02:19
This is weird. I can reproduce the problem in the release code. I wonder if there is a Python version problem here. I'll test out your fix.

**Comment by jedwards4b** [comment] 2019-02-05 15:41
Can you point me to your release case that is failing?

**Comment by dabail10** [comment] 2019-02-05 21:44
I have a copy of cesm2_1_0 checked out in:

/glade/work/dbailey/cesm2_1_0

My case is:

/glade/u/home/dbailey/cesm_runs/dtest_cesm2

I just run preview_namelist to see the problem.

Dave

**Comment by jedwards4b** [comment] 2019-02-05 21:47
@dabail10 you checked out cesm2_1_0 but then it appears you updated the cice component to master before you ran the test.  Try again with  cice5_20181109

**Comment by dabail10** [comment] 2019-02-05 21:48
I took the fix out of this version and it gives the same behaviour.

Dave

**Comment by jedwards4b** [comment] 2019-02-05 22:34
Just to document what we figured out - I was testing a B case and Dave a D case - the D case is always a startup but B is hybrid on the release branch and startup on master - the code in question is in an if startup branch in buildnml.  So this fix does need to be applied to the release as well as master.

**Closed** 2019-02-05 22:34 UTC
