### ISSUE TITLE
dt limit problem with gregorian forcing stream data for datm for a no_leap simulation.

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3135] opened 2019-06-06 18:14 UTC
This is with cime5.6.16 on cheyenne with intel compiler and without the true ESMF library (USE_ESMF_LIB: FALSE).

@olyson reports this.

The model dies with gregorian forcing data:

> scripts/clm50_release-clm5.0.24_1deg_PrincetonV2_1850AD> ncdump -h /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.Princeton.0.5d.v2.c190604/clmforc.PRINCETON2.c2019.0.5x0.5.Prec.1920-03.nc
> netcdf clmforc.PRINCETON2.c2019.0.5x0.5.Prec.1920-03 {
> dimensions:
> 	scalar = 1 ;
> 	lon = 720 ;
> 	lat = 360 ;
> 	time = 248 ;
> variables:
> 	float time(time) ;
> 		time:units = "days since 1920-03-01 00:00:00" ;
> 		time:long_name = "observation time" ;
> 		time:calendar = "gregorian" ;

and  no_leap calendar CALENDAR: NO_LEAP

The model dies with a dt limit error on year 100. Note: this is a year that is NOT a leap year even though divisible by 4. Other years were fine in coming up to this point.

atm.log:

> (shr_dmodel_readstrm) file ub: /glade/p/cgd/tss/CTSM_datm_forcing_data/atm_forcing.datm7.Princeton.0.5d.v2.c190604/clmforc.PRINCETON2.c2019.0.5x0.5.Prec.1920-03.nc       1
>  (shr_strdata_advance) ERROR: for stream            2
>  (shr_strdata_advance) ERROR: dt limit1   0.875000000000000     
>   0.125000000000000        1.50000000000000     
>  (shr_strdata_advance) ERROR: dt limit2      1000229       81000     1000301
>         5400
>  ERROR: (shr_strdata_advance) ERROR dt limit for stream
> 
> 

cesm.log:

> 35:        5400
> 35: ERROR: (shr_strdata_advance) ERROR dt limit for stream
> 10: (shr_strdata_advance) ERROR: dt limit1   0.875000000000000
> 10:  0.125000000000000        1.50000000000000
> 10: (shr_strdata_advance) ERROR: dt limit2      1000229       81000     1000301
> 10:        5400
> 10: ERROR: (shr_strdata_advance) ERROR dt limit for stream
> 2:Image              PC                Routine            Line        Source
> 2:cesm.exe           00000000019B220D  Unknown               Unknown  Unknown
> 2:cesm.exe           0000000001131C32  shr_abort_mod_mp_         114  shr_abort_mod.F90
> 2:cesm.exe           00000000012685B8  shr_strdata_mod_m         777  shr_strdata_mod.F90
> 2:cesm.exe           00000000004DF50C  datm_comp_mod_mp_         664  datm_comp_mod.F90
>

**Comment by ekluzek** [comment] 2019-06-07 20:33
Note, that it also dies with USE_ESMF_LIB=TRUE. Although it doesn't give a clean error like above. But, that probably means it's not inside the ESMF library level, but in datm at a higher level.

Here's the end of the cesm.log file...

> 0: memory_write: model date =   01000228       0 memory =   66777.58 MB (highwater)        135.59 MB (usage)  (pe=    0 comps= ATM ESP)
> 36:  size=17197081 rss=44674 share=10280 text=7170 datastack=0
> 29:MPT ERROR: Rank 29(g:29) is aborting with error code 1.
> 29:	Process ID: 34554, Host: r1i0n17, Program: /gpfs/fs1/scratch/oleson/clm50_release-clm5.0.24_1deg_PrincetonV2_USEESMFLIBTRUE_1850AD/bld/cesm.exe
> 29:	MPT Version: HPE MPT 2.19  12/07/18 05:31:15
> 29:
> 29:MPT: --------stack traceback-------
> -1:MPT ERROR: MPI_COMM_WORLD rank 10 has terminated without calling MPI_Finalize()
> -1:	aborting job
>

**Comment by billsacks** [comment] 2021-11-03 21:05
@ekluzek @olyson - any feelings on how important it is to fix this for the CESM2.1 series or just make sure it works with CDEPS?

**Comment by ekluzek** [comment] 2021-11-03 21:08
I'd say we wouldn't need to fix this in CESM2.1, and that as long as it works right in CDEPS that would be sufficient. I don't think that Keith see's cime issues, so let's ask him tomorrow.

**Comment by olyson** [comment] 2021-11-03 21:31
Probably not worth worrying about in CESM2.1.  Actually, I don't see calendar = 'gregorian' on the those forcing files any more, so we might have got around this issue by removing the leap day from the forcing data and setting the calendar to 'no_leap' (my vague recollection).  So we're not going to be able to reproduce this issue with this data anyway.  I personally haven't run across this problem with any other forcing datasets since then.  I don't think any of our other global forcing datasets use gregorian.
If the NEON tower sites use gregorian and CDEPS, then maybe the issue could be addressed in that framework?

**Closed** 2021-11-04 22:32 UTC
Labels: ty: Bug, tp: data models, maint-5.6_bugfix, postsplit
