### ISSUE TITLE
cime5.3.0-alpha.07 unable to handle RESUBMIT > 1

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#1672] opened 2017-06-09 22:18 UTC
I've built a single instance WACCM case (FWscHIST) and started it 
from default initial conditions.
I set RESUBMIT = 3 and DOUT_S = TRUE, so that st_archive 
submits the next job.
The first month ran fine, but the automatic resubmission failed:

MPT: Launch error on r1i0n5.ib0.cheyenne.ucar.edu
/glade/u/apps/opt/mpt/2.15-sgi715a158/bin/omplace: 
line 640: 25449 Segmentation fault      (core dumped) dplace -p $placefile "$@"

Manually resubmitting the job led to another successful month,
and another failed resubmission.

Kevin Raeder.

**Comment by mvertens** [comment] 2017-06-10 19:31
What cesm tag are you using?

**Comment by kdraeder** [comment] 2017-06-10 23:54
Hi Mariana,

2_0_alpha06i

Kevin

**Comment by jgfouca** [comment] 2017-06-14 16:58
Cheyenne issue?

**Comment by jedwards4b** [comment] 2017-06-14 17:17
Yes this is a Cheyenne issue and we are working with cisl to resolve it.

**Comment by billsacks** [comment] 2017-06-14 19:07
Is the problem that we can't submit jobs from the compute nodes on cheyenne? If so, should this be documented as a cime requirement in http://esmci.github.io/cime/users_guide/porting-cime.html ? Or is this something that is assumed to work on pretty much every machine... except cheyenne?

**Comment by jedwards4b** [comment] 2017-06-14 19:10
I have been unable to reproduce the reported problem, I've sent email to Kevin to clarify.

**Comment by kdraeder** [comment] 2017-06-14 19:33
Thanks for looking into this!

The case I had trouble running on cheyenne is
/glade/p/work/raeder/Exp/WSD_spinup_1deg_sst.25.
The run and archive directories are in
/glade/scratch/raeder/WSD_spinup_1deg_sst.25/{run,archive}

I haven't tried to run a job with RESUBMIT > 0 since then,
but I'm trying to set one up now for other reasons.

Kevin

**Comment by jedwards4b** [comment] 2017-06-14 19:53
In your original error message you posted:
```
MPT: Launch error on r1i0n5.ib0.cheyenne.ucar.edu
/glade/u/apps/opt/mpt/2.15-sgi715a158/bin/omplace:
line 640: 25449 Segmentation fault (core dumped) dplace -p $placefile "$@"
```
The very next message in that file was
```
See log file for details: /glade/scratch/raeder/WSD_spinup_1deg_sst.25/run/cesm.log.170601-133844
```
Checking the log file I find:
```
170: ERROR initInterp set_mindist: Cannot find any input points matching output point:
170: subgrid level, index = pft                   575673
170: ltype:            4
170: ctype:          409
170: ptype:            0
170:  
170: Consider rerunning with the following in user_nl_clm:
170: init_interp_fill_missing_with_natveg = .true.
170: However, note that this will fill all missing types in the output
170: with the closest natural veg column in the input
170: (using bare soil for patch-level variables).
170: So, you should consider whether that is what you want.
170: ENDRUN:ERROR in initInterpMindist.F90 at line 220           
```
This is a clm error and not  a cime error as reported - I'm not sure why it's working when you resubmit by hand.

**Comment by kdraeder** [comment] 2017-06-14 20:31
It's true that the first time I tried to run the first month
I had this CLM error.  I fixed it in the clm namelist
and successfully ran the first month with RESUBMIT=0.
(/glade/p/work/raeder/Exp/WSD_spinup_1deg_sst.25/
   WSD_spinup_1deg_sst.25.run.o1229798)

I submitted the 2nd month with RESUBMIT=3.
That month ran (WSD_spinup_1deg_sst.25.run.o1230435),
and the st_archive submitted month 3,
which failed       (WSD_spinup_1deg_sst.25.run.o1230570):
-----
run command is mpiexec_mpt -p "%g:"  omplace
      /glade/scratch/raeder/WSD_spinup_1deg_sst.25/bld/cesm.exe >> 
cesm.log.$LID 2>&1
ERROR: RUN FAIL: Command 'mpiexec_mpt -p "%g:"  omplace 
/glade/scratch/raeder
      /WSD_spinup_1deg_sst.25/bld/cesm.exe  >> cesm.log.$LID 2>&1 ' failed
See log file for details:
/glade/scratch/raeder/WSD_spinup_1deg_sst.25/run/cesm.log.170601-184528
-----
which says
-----
/glade/u/apps/opt/mpt/2.15-sgi715a158/bin/omplace: line 640: 62394 
Segmentation fault
      (core dumped) dplace -p $placefile "$@"
MPT ERROR: could not run executable. If this is a non-MPT application,
you may need to set MPI_SHEPHERD=true.
-----

I thought it might be a transient machine problem,
so I submitted month 3 manually, which ran 
(WSD_spinup_1deg_sst.25.run.o1232070).
St_archive submitted month 4, which failed in the same way
(WSD_spinup_1deg_sst.25.run.o1232395)

I ran the remaining 2 months one at a time with RESUBMIT=0.
I had what I needed, and was/am worn out from trying to make
things work on cheyenne, so I didn't pursue the MPI_SHEPARD
suggestion, other than seeing that it's not available in the $CASE
directory.

Kevin

**Comment by billsacks** [comment] 2017-06-14 20:39
@JeremyFyke recently reported a MPI_SHEPHERD error on cheyenne, too. My understanding (maybe wrong) was that this was from the initial submission of the run, not a resubmit. His message:

> Hi Bill,
>  
> I managed to get one 5 day BG simulation through Cheyenne quite easily.  That is great.
>  
> However, when I tried another, this time with an attempt to do a hybrid run, I received this fatal error:
>  
> => tail cesm.log.170609-162518 
> MPT: Launch error on r1i1n33.ib0.cheyenne.ucar.edu
> MPT ERROR: could not run executable. If this is a non-MPT application,
> you may need to set MPI_SHEPHERD=true.
>

**Comment by jedwards4b** [comment] 2017-06-14 20:54
The MPT_SHEPHERD error is an indication that the mpiexec_mpt did not recognize your program as being an mpi program.   It doesn't really make any sense but we are seeing it intermittently when submitting jobs from compute nodes on cheyenne.

**Comment by kdraeder** [comment] 2017-06-23 20:17
This is becoming more pressing for me, so I'm interested to hear what
the status is and what CISL is saying.

I need to hand this software off to Julio Bacmeister for an ASD project,
so it would be very helpful if the resubmission-from-st_archive works.
As I noted above, I've now had the same problem while using cesm2_0_beta05.
Does this look like "not my fault", and/or can anyone suggest ways to debug this?

Thanks,
Kevin

**Comment by kdraeder** [comment] 2017-06-30 22:50
I've done some more testing of this, and found that I can't
reproduce the problem in cesm2_0_alpha06i.  
This is the version which is closest to the sandbox given
to me to work with  and which I could conveniently 
get to work with DART.
(misc02_cam5_4_120; has more WACCM-X in it
and other differences I don't have time to identify) 

I was trying to build FWscHIST, which is in misc02, 
but not in alpha06i.  My latest test built FWscAMIP, 
which is in aslph06i, but not in misc02.

So I guess this issue should be closed, 
since it's not a community problem.

Thanks for your help and suggestions.

Kevin

**Comment by billsacks** [comment] 2017-07-01 02:01
@kdraeder thanks for testing this. I'll close it for now, and if you run into it again, we can reopen it.

**Closed by billsacks** 2017-07-01 02:01 UTC
Labels: Assigned, machine specific, tp: script tools, ty: Bug
