### ISSUE TITLE
Error in atm/ocn flux calculation

### ISSUE THREAD

**Issue by amametjanov** [ESMCI/cime#2340] opened 2018-03-02 23:56 UTC
This is occurring in E3SM high-res coupled runs on Theta: in a restart run after the first simulation-hour when ATM and OCN couple:
```
ERROR: No iterations performed ERROR in shr_flux_mod.F90 at line 388
Image              PC                Routine            Line        Source
acme.exe           000000000387F9BC  shr_abort_mod_mp_         114  shr_abort_mod.F90
acme.exe           0000000003935D06  shr_flux_mod_mp_s         388  shr_flux_mod.F90
acme.exe           000000000049F6AB  seq_flux_mct_mp_s        1439  seq_flux_mct.F90
acme.exe           00000000004172AC  cime_comp_mod_mp_        2308  cime_comp_mod.F90
acme.exe           00000000004280A3  MAIN__                    103  cime_driver.F90
```

Git history shows recent changes in ESMCI/cime#2180.

**Comment by PeterCaldwell** [comment] 2018-03-03 00:19
Email comment from @rljacob : 

> Yes this was recently made to be more like a true iterative method.  See
this comment:
https://github.com/ESMCI/cime/pull/2180#issuecomment-355311518

The condition that failed and produced that error message is:
  abs((ustar - ustar_prev)/ustar) > flux_con_tol .and.
iter < flux_con_max_iter

Its unlikely the last part failed so what's evaluating to false is

abs((ustar - ustar_prev)/ustar)) > 0.0

Possibly a problem with the "abs" function on Theta?

**Comment by PeterCaldwell** [comment] 2018-03-03 00:27
Email comment from @mt5555 - 

> I dont know anything about that code.  But I read through the github issues anyway. If the argument to the abs() function is zero, then the new code will not do 2 iterations, and thus wont match the old code?  To force 2 iterations, may need to change to: abs((ustar - ustar_prev)/ustar) >= flux_con_tol

**Comment by PeterCaldwell** [comment] 2018-03-03 00:30
Good point Mark. At first I was wondering how the argument to the abs function could be zero without blowing up due to 0/0 condition, but actually this will be the case whenever ustar==ustar_prev. It seems like backwards compatability really does require ">=" rather than ">". In other words, ">" seems like a logical bug even if it isn't the reason why our code is crashing.

**Comment by mt5555** [comment] 2018-03-03 00:59
Based on the error message, I thought the code was crashing because it didn't perform any iterations, which would be the case if ustar==ustar_prev.  Thus there is  a chance changing to >= will actually fix this crash.

**Comment by PeterCaldwell** [comment] 2018-03-03 01:07
I've changed my mind. I don't think ">=" can explain the problem. The problem is ostensibly that  abs((ustar - ustar_prev)/ustar) > flux_con_tol is false. Just before this conditional is the line ustar_prev = ustar*2.0r8. Substituting ustar_prev into the conditional yields 1>flux_con_tol. I'm pretty sure flux_con_tol is supposed to be 0 for E3SM, so the conditional should always be true, regardless of whether we use ">=" or just ">".

**Comment by PeterCaldwell** [comment] 2018-03-03 01:29
I'd suggest everyone running high-res on theta (@amametjanov , @jonbob , and Qi Tang) add the following just before line 388 of cime/src/share/util/shr_flux_mod.F90 so next time our code fails, we at least have useful debugging info:
``            write(s_logunit,*) 'iter,flux_con_max_iter = ',iter,flux_con_max_iter
``           write(s_logunit,*) 'ustar,ustar_prev,flux_con_tol = ',ustar,ustar_prev,flux_con_tol

I just submitted a M-sized job for an hour with this change.

**Comment by rljacob** [comment] 2018-03-03 02:45
The full conditional in the while statement is
`(abs((ustar - ustar_prev)/ustar) > flux_con_tol .and. iter < flux_con_max_iter)`

With E3SM values for the flux_con* variables and ustar_prev = 2*ustar initially, the first evaluation of that conditional should be
(abs(-1) > 0 .and. 0 < 2)

Which is always b true.  Iter is set to 1 in the first line of the while loop so the error condition producing that message (if iter < 0)  can only be reached if flux_con_max_iter < 1 (which would be user error) or the abs() is evaluating to negative.

**Comment by mt5555** [comment] 2018-03-03 14:53
seems like the most likely is 0/0, and then abs(NaN) > 0 is false, exiting the loop.  so how about 

  abs(uster-uster_prev) > flux_con_tol*abs(ustar)

to reproduce the old code.

**Comment by jedwards4b** [comment] 2018-03-03 15:41
As @rljacob points out there is no logical way that the code would not enter that loop - you need to add some print statements and see if you can determine what's gone wrong.   ustar can't be 0 here either so I don't think it's a NaN issue.

**Comment by PeterCaldwell** [comment] 2018-03-03 18:01
I ran 2 more cases on 863 nodes. Because I'm using a run_acme script which handles all aspects of model config/build/run, I can say with confidence these jobs are identical except for their walltime, run name, and the addition of a couple print statements mentioned above. My two jobs both failed in the first few steps, but for different reasons (below). Thus I think it's pretty clear theta is suffering from memory corruption, use of uninitialized junk, or something like that.  

/projects/ClimateEnergy_2/caldwell/ACME_simulations/theta.master-2-28-18.1950try6-M.ne120_oRRS18v3_ICG failed with "forrtl: severe (154): array index out of bounds" on line 288 of  rrtmg_sw_taumol.f90. 

/projects/ClimateEnergy_2/caldwell/ACME_simulations/theta.master-2-28-18.1950try6.2.ne120_oRRS18v3_ICG/ died with "check_downscale_consistency ERROR: column-level forcing differs from gridcell-l" on line 114 of shr_abort_mod.F90

These are in addition to the error I reported last night from /projects/ClimateEnergy_2/caldwell/ACME_simulations/theta.master-2-28-18.1950try6.1.ne120_oRRS18v3_ICG, which died with "No iterations performed ERROR in shr_flux_mod.F90 at line 388"

**Comment by PeterCaldwell** [comment] 2018-03-03 18:08
Ok, I've submitted a job compiled in debug mode. Perhaps that will give more useful/reproducible error info.
@amametjanov - have you confirmed that if you run 2 identical runs on theta they will be bfb reproducible? Given my experience above, this seems doubtful.

**Comment by rljacob** [comment] 2018-03-03 21:44
This doesn't look like  a CIME issue so closing this here.  We can reopen in ACME-Climate.

**Closed** 2018-03-03 21:44 UTC
