### ISSUE TITLE
Document test_mods and test options

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#2115] opened 2017-12-06 00:27 UTC
Document how to create and use test_mods

Also document test name options like "P" or "R".

**Comment by billsacks** [comment] 2017-12-06 19:02
> Document how to create and use test_mods

This will be done as part of #1964 

> Also document test name options like "P" or "R".

This is partly done in the documentation that I'll pull in as part of #1964 ... I document _D _L and _P, since those are the three I use and see most often. I don't know what _R does myself....

**Comment by jgfouca** [comment] 2017-12-13 20:27
test_scheduler._create_newcase_phase, test_scheduler._xml_phase

**Comment by billsacks** [comment] 2017-12-13 20:28
Closing as duplicate of #1964

**Closed by billsacks** 2017-12-13 20:29 UTC
Labels: Assigned, st: duplicate, tp: documentation
