### ISSUE TITLE
userdefined machine method should be documented

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#478] opened 2016-08-30 16:35 UTC
Setting up a "userdefined" machine is no longer an option for cesm acme. The minimum that would need to be done to add this functionality would be to add a "userdefined" machine to config_machines.xml in either cesm or acme. 

This is a useful option to have in order for people to run simple configurations for testing on their laptop, or for university users to get a start on configuring their own machine.

**Comment by jedwards4b** [comment] 2016-08-30 16:39
We have an alternative method for this now.   You can now put config_machines.xml, config_batch.xml and/or config_compilers.xml in a directory $HOME/.cime and they will be appended to the objects read from the cime_config directories.    These files, once created, should continue to work across multiple cime versions.     We will provide templates for these in documentation.

**Comment by billsacks** [comment] 2017-05-13 19:00
Closing as a duplicate of #1293

**Closed by billsacks** 2017-05-13 19:00 UTC
Labels: documentation
