### ISSUE TITLE
Bring back provenance info in README.case

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#311] opened 2016-08-01 18:02 UTC
cime2 left lots of good info in README.case after create_newcase was run.   This is all missing from the latest cime.  Can it be added back?

Example:
create_newcase -case Fcase -compset F -res f19_g16 -mach blues -compiler intel -project ACME

Would result in the following:
Component set: longname (shortname) (alias) 
  2000_CAM4_CLM40%SP_CICE%PRES_DOCN%DOM_RTM_SGLC_SWAV (F_2000) (F) 
Component set Description: 
  CAM: CLM: RTM: CICE: DOCN: SGLC: SWAV: present day: cam4 physics: clm4.0 physics: clm4.0 Satellite phenology: presc
ribed cice: docn data mode: 
Grid: 
  a%1.9x2.5_l%1.9x2.5_oi%gx1v6_r%r05_m%gx1v6_g%null_w%null (1.9x2.5_gx1v6) 
  ATM_GRID = 1.9x2.5  NX_ATM=144 NY_ATM=96 
  LND_GRID = 1.9x2.5  NX_LND=144 NX_LND=96 
  ICE_GRID = gx1v6  NX_ICE=320 NX_ICE=384 
  OCN_GRID = gx1v6  NX_OCN=320 NX_OCN=384 
  ROF_GRID = r05  NX_ROF=720 NX_ROF=360 
  GLC_GRID = null  NX_GLC=0 NX_GLC=0 
  WAV_GRID = null  NX_WAV=0 NX_WAV=0 
Grid Description: 
  null is no grid: 1.9x2.5 is FV 2-deg grid: gx1v6 is Greenland pole v6 1-deg grid: r05 is 1/2 degree river routing g
rid: 
Non-Default Options: 
  ATM_NCPL: 48 
  BUDGETS: FALSE 
  CAM_CONFIG_OPTS: -phys cam4 
  CAM_DYCORE: fv 
  CCSM_BGC: CO2A 
  CCSM_CCOST: 0 
  CCSM_CO2_PPMV: 367.0 
  CICE_MODE: prescribed 
  CLM_CO2_TYPE: diagnostic 
  CLM_CONFIG_OPTS: -phys clm4_0 
  CLM_NML_USE_CASE: 2000_control 
  COMP_ATM: cam 
  COMP_GLC: sglc 
  COMP_ICE: cice 
  COMP_LND: clm 
  COMP_OCN: docn 
  COMP_ROF: rtm 
  COMP_WAV: swav 
  CPL_ALBAV: false 
  CPL_EPBAL: off 
  CPL_SEQ_OPTION: CESM1_MOD_TIGHT 
  DOCN_MODE: prescribed 
  OCN_NCPL: $ATM_NCPL 
  ROF_NCPL: 8 
  RTM_BLDNML_OPTS: -simyr 2000 
  RTM_MODE: ACTIVE 
  SCIENCE_SUPPORT: NO 
  SSTICE_DATA_FILENAME: $DIN_LOC_ROOT/atm/cam/sst/sst_HadOIBl_bc_1x1_clim_c101029.nc 
  SSTICE_GRID_FILENAME: $DIN_LOC_ROOT/ocn/docn7/domain.ocn.1x1.111007.nc 
  SSTICE_STREAM: CAMDATA 
  SSTICE_YEAR_ALIGN: 1 
  SSTICE_YEAR_END: 0 
  SSTICE_YEAR_START: 0

In the latest cime, only the create_newcase line is there.

**Comment by jedwards4b** [comment] 2016-08-01 18:42
Yes I've added back the component and grid info in my branch.  The non-default options will take a bit more work.

**Comment by jedwards4b** [comment] 2016-08-01 19:27
This turns out to be a little more involved - the issue is that the case directory and therefor the README file is not yet created when this information is available.   We will need to piece it back together after creating the README - what I have so far:
```
2016-08-01 13:20:38: /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/Tools/../../scripts/create_newcase --case /gla
de/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/ERI.f19_g16.X.yellowstone_intel.20160801_192037 --res f19_g16 --mach ye
llowstone --compiler intel --compset X --project P93300606 --test --walltime 00:10
2016-08-01 13:20:38: Compset longname is 2000_XATM_XLND_XICE_XOCN_XROF_XGLC_XWAV
2016-08-01 13:20:38: Compset specification file is /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/Tools/../../driv
er_cpl/cime_config/config_compsets.xml
2016-08-01 13:20:38: Pes     specification file is /glade/p/work/jedwards/sandboxes/cesm2_0_alpha/cime/scripts/Tools/../../driv
er_cpl/cime_config/config_pes.xml
```

**Comment by jedwards4b** [comment] 2017-04-11 22:03
@rljacob After reviewing I think that this issue can be closed.   All of the information above is in README.case except the non-default options which are in CaseStatus.

**Comment by jedwards4b** [comment] 2017-05-09 14:14
Since there have been no further comments I'm closing this.

**Closed by jedwards4b** 2017-05-09 14:14 UTC
Labels: ready
