### ISSUE TITLE
Gfortran 8.x build issue 

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#2821] opened 2018-09-27 21:30 UTC
The test SMS_D_Ln9.f19_g16_rx1.A.   is failing on a number of platforms when using gfortran v 8.1 or 8.2.   The issue seems to be related to the gfortran debug flags, the test passes if DEBUG=FALSE.

The compiler is reporting an error in compiling the file piodarray.F90 but the line number indicated by the error doesn't match the source file.   I spent some time trying to reduce the problem to something reportable or to determine the compiler flag responsible for the issue, but have been unable to do so.

**Comment by dqwu** [comment] 2018-10-19 19:17
@jedwards4b @jayeshkrishna 
This issue is also reproducible on anlworkstation with Gfortran 6.x

PR 2811 modified scripts/Tools/Makefile and added "-DDEBUG" to CPPDEFS
when DEBUG mode is enabled. 
```
# Unless DEBUG mode is enabled, use NDEBUG to turn off assert statements.
ifeq ($(strip $(DEBUG)),TRUE)
   CPPDEFS += -DDEBUG
else
   CPPDEFS += -DNDEBUG
endif
```
Since SMS_D_Ln9.f19_g16_rx1.A is a test using DEBUG mode, the macro DEBUG
will be defined to build PIO's Fortran code:
`CMAKE_Fortran_FLAGS:STRING="... -DDEBUG ..."`

There is an issue in src/externals/pio1/pio/piodarray.F90.in, line 1318
`if(DEBUG) print *,__PIO_FILE__,__LINE__,status, ierr, total_buffsize`

Before PR 2811 is merged, the above if statement is OK, as Fortran is **case insensitive**
for variables. There is no defined macro called "DEBUG", so "DEBUG" will be exactly the
same as "Debug" (a public logical variable defined in pio_support.F90)

After PR 2811 is merged, "DEBUG" macro is defined and its value is 1
The Fortran preprecessor converts the above if statement to
`if(1) print *,__PIO_FILE__,__LINE__,status, ierr, total_buffsize`
This will cause a build error like:
```
    if(DEBUG) print *,__PIO_FILE__,__LINE__,status, ierr, total_buffsize
      1
Error: IF clause at (1) requires a scalar LOGICAL expression
```
Because macro substitution is **case sensitive** for Fortran, a simple fix is to replace
line 1318 of src/externals/pio1/pio/piodarray.F90.in with:
`if(Debug) print *,__PIO_FILE__,__LINE__,status, ierr, total_buffsize`
Note: other if statements in piodarray.F90.in already use "if(Debug)"

**Comment by dqwu** [comment] 2018-10-19 19:46
It seems that @jgfouca has committed a fix to the master branch.

**Comment by jgfouca** [comment] 2018-10-19 19:49
Sorry all, didn't notice this issue. Yes, it has been fixed.

**Closed by jgfouca** 2018-10-19 19:49 UTC
