### ISSUE TITLE
case.run should not run preview_namelist (at least by default)

### ISSUE THREAD

**Issue by mfdeakin-sandia** [ESMCI/cime#1575] opened 2017-05-19 20:40 UTC
case.run is taking 17 minutes of batch time to run CIME and preview namelist on Edison, so the critical path team would like it to not run preview_namelist by default.
I believe this can be done just for ACME in case CESM doesn't want this change.

**Comment by billsacks** [comment] 2017-05-20 20:37
I think you mean that preview_namelist is being run by case.run, since I assume that having case.submit run preview_namelist wouldn't take any batch time (since that's typically done from the logic node)? Is that what the `--skip-preview-namelist` (added by #1471 ) addressed? If so, are you thinking that we (or ACME) should just change the default behavior so that `--skip-preview-namelist` is true by default?

With the changes over the last few months, I have lost track of when preview_namelist is currently run. Can someone please comment on:

1. When is preview_namelist _always_ run, with no way to bypass it?

2. When is preview_namelist run by default, but with a way to bypass it?

**Comment by rljacob** [comment] 2017-05-21 04:02
I've been trying to think of a way to document this along with everything else done for you betweeen the basic "case" commands a user executes.  What gets locked and when and how to back up.

**Comment by billsacks** [comment] 2017-05-21 11:20
@rljacob - that would be fantastic - thanks for thinking about this.

**Comment by rljacob** [comment] 2017-05-22 17:41
I think we'll need to add a control variable for "should preview_namelist be run in case.run" and ACME can set the default to FALSE while CESM sets it to TRUE.

**Comment by rljacob** [comment] 2017-05-23 05:44
This is a duplicate of #1278

**Comment by jgfouca** [comment] 2017-11-13 22:47
I see this comment right before the call to preview_namelists in case_run.py:

```
# This needs to be done everytime the LID changes in order for log files to be set up correctly 
```

This implies skipping preview_namelists is not safe in the case where a problem does multiple LID runs, which can happen for many test types, node-fail retries, and when there are multiple data assimilation cycles. Therefore, I don't think it's wise to make skipping it the default behavior.

**Closed by jgfouca** 2017-11-13 22:47 UTC
Labels: Assigned, tp: user interface, ty: enhancement
