### ISSUE TITLE
Recent CIMEs fail scripts_regression_tests.py on cheyenne.

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2409] opened 2018-03-29 15:52 UTC
I have a cesm2_0_alpha08, which I downloaded 
after the cheyenne /glade/p failure. 
I've imported CIME (circa 2018-3-28 15:30) into it with
> git clone https://github.com/ESMCI/cime.git
and immediately ran scripts_regression_tests.py.
It failed in the run of the PET test.

An earlier version of cime (circa 2018-3-1) fails in the DAE run
because the datm_in file wasn't found in $DAE_test/run/case2run,
even though it exists in the parent directory.

It seems most likely to me that there's something wrong with
my/cheyenne's environment, since this regression testing is
supposed to be an early hurdle to having changes committed.
I hardly know where to look for clues, so if anyone feels
like poking around in 
/glade2/scratch2/raeder/cesm2_0_alpha08/cime/scripts/tests/scripts_regression_tests.py.log.22024   (the PET failure)
and/or
/glade2/scratch2/raeder/cesm2_0_alpha08/cime5.4.0-alpha.25/scripts/tests/scripts_regression_tests.py.log.63560    (the DAE failure)
I'd be very thankful.

**Comment by jedwards4b** [comment] 2018-03-29 15:54
This is a duplicate of issue #2408

**Closed by jedwards4b** 2018-03-29 15:54 UTC
Labels: tp: script tools, tp: system tests, tp: unit tests, ty: help wanted

**Comment by jedwards4b** [comment] 2018-03-29 15:58
@kdraeder at the moment if the PET is your only failing test in scripts_regression_tests.py you should consider your testing good.

**Comment by kdraeder** [comment] 2018-03-29 20:27
@jedwards4b 
Thanks!
I made a minor regex change to case_st_archive.py  and told 
cesm/config_archive.xml:dart to look for a list of restart history files in a dart.r. file. 
I didn't provide a dart.r file in the tests. 

PET still fails.  Scripts_regression_tests.py now says that tests ERI and ERIO
that were PEND in the first test are now FAIL.  
Should I ignore those too?

**Comment by jedwards4b** [comment] 2018-03-29 21:04
No you should not ignore those - those tests are significant to the changes you are making.  PET is now fixed on master if you want to rebase or merge to the latest.

**Comment by jedwards4b** [comment] 2018-03-29 22:01
I was testing a new inputdata download feature and choose that particular file to test with, I should have set up my own temporary DIN_LOC_ROOT - I'll do that now.

**Comment by kdraeder** [comment] 2018-03-30 19:45
I reran the regressions with none of my changes.
They passed, except for the PET test.
I put my changes in, and they still passed, except for PET.
So I downloaded the latest CIME yesterday afternoon to get past the PET failure.
I saw that there had been no updates to the 2 files I've modified,
so I imported those into the new CIME.   Since then the regression
tests have failed a half dozen times for no apparent reason.
They just stop at some random stage with no error messages
or emails.   Except the last one gave me a core file!  I'll be
trying to identify the executable to use with gdb and this core file,
but if you have any suggestions or context, I'd love to hear it.
Like, can you tell me about anyone else who's successfully
running scripts_regression_tests.py on cheyenne?

Also, in the "successful" tests I've been getting emails telling me that
PBS Job Id: 6551183.chadmin1
Job Name:   SMS_Ln9_P1.f19_g16_rx1.A.cheyenne_intel.fake_testing_only_20180330_101155.test
Post job file processing error; job 6551183.chadmin1 on host r8i4n0

**Comment by jedwards4b** [comment] 2018-03-30 19:47
How are you running scripts_regression_tests.py?   You can't run it on a login node,
I use:
```
qcmd -l walltime=02:00:00 -- ./scripts_regression_tests.py
```

**Comment by kdraeder** [comment] 2018-03-30 19:50
qcmd -A P86850054 -q share -l walltime=1:20:00 \
     -l select=1:ncpus=4:mpiprocs=4 \
     -- ./scripts_regression_tests.py

**Comment by jedwards4b** [comment] 2018-03-30 19:53
The scripts_regression_tests.py uses threading and may exceed the requested 4 cpus, try removing the -q share so that you get all of the resources of a full node.

**Comment by kdraeder** [comment] 2018-03-30 23:10
That seems to have fixed it.  Or it was a coincidence.
So this issue can be closed.
