### ISSUE TITLE
Wrong pio_iotype being set

### ISSUE THREAD

**Issue by fischer-ncar** [ESMCI/cime#351] opened 2016-08-08 21:38 UTC
PIO_TYPENAME=pnetcdf in env_run.xml isn't being carried over to the model run. The pio_iotype in the cpl.log shows it's being set to 6, serial netcdf, instead of 5 for pnetcdf. This started happening with cesm1_5_alpha07d, with the cime5.4.16 tag, pull request #454. This bug is also in cesm2.
@Katetc @mvertens @ekluzek @jedwards4b

**Comment by jedwards4b** [comment] 2016-08-08 21:55
Testing a fix now.   Note that the root cause of this was a refactor of driver_cpl/bld/build-namelist which combined several different xml definition files  "namelist_definition_drv.xml", "namelist_definition_drv_flds.xml", "namelist_definition_modio.xml"   into a single xml object in memory - this caused different definitions of pio_typename contained in these files to be merged and the first one to be lost.

**Comment by jedwards4b** [comment] 2016-08-09 22:19
Fixed in PR #357

**Closed by jedwards4b** 2016-08-09 22:19 UTC
