### ISSUE TITLE
Running on Titan with "sub-projects"

### ISSUE THREAD

**Issue by mrnorman** [ESMCI/cime#1398] opened 2017-04-21 16:17 UTC
I'm trying to run a case on Titan with a project called "csc190acme" (a sub-project of csc190), and it's failing.

The problem is that I need the case.run to use the queue option "-A csc190acme" while having the rest of ACME use the folder "/lustre/atlas/scratch/imn/csc190". If I set the PROJECT variable in env_batch.xml to csc190, then when I do ./case.submit, I get:

Submitting job script qsub    -q debug -l walltime=01:00:00 -A csc190 case.run 
ERROR: Command: 'qsub    -q debug -l walltime=01:00:00 -A csc190 case.run ' failed with error ''

Yet, when I set PROJECT to csc190acme, I get:

ERROR: Could not make directory '/lustre/atlas/scratch/imn/csc190acme/FC5AV1C-L_ne16_mmf/run', error: [Errno 13] Permission denied: '/lustre/atlas/scratch/imn/csc190acme'

In the past, I was able to handle this by just changing the run script to have the full project name.

We need a means of specifying an appendage to the project so that ACME simultaneously uses the base project name for the folder and uses the full project name for the queue system.

**Comment by jedwards4b** [comment] 2017-04-21 17:48
I think that if you use the correct project code and the --output-root option to create_newcase you can get the configuration you are looking for.

**Comment by rljacob** [comment] 2017-04-22 02:30
This is a duplicate of https://github.com/ESMCI/cime/issues/1332 but Jim's suggestion should work.

**Closed by rljacob** 2017-04-22 02:30 UTC
Labels: CRITICAL, machine files
