### ISSUE TITLE
Having long wait time on case.submit

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3036] opened 2019-03-11 00:52 UTC
This is with cime5.6.12

I'm having long wait times on running case.submit on cheyenne today, with it eventually failing as we see below. It seems to be because of some type of network issue getting to svn inputdata from cheyenne. I'm wondering if we need another --skip option to skip checking the connection to inputdata?

```
   Calling /gpfs/fs1/scratch/erik/release-clm5.0.19/cime/src/components/stub_comps/swav/cime_config/buildnml
   Calling /gpfs/fs1/scratch/erik/release-clm5.0.19/cime/src/components/stub_comps/sesp/cime_config/buildnml
   Calling /gpfs/fs1/scratch/erik/release-clm5.0.19/cime/src/drivers/mct/cime_config/buildnml
Finished creating component namelists
Checking that inputdata is available as part of case submission
Client protocol gftp not enabled
Using protocol wget with user anonymous and passwd user@example.edu
ERROR: Could not connect to repo '{0}'
This is most likely either a proxy, or network issue .
```

**Comment by jedwards4b** [comment] 2019-03-11 13:27
Duplicate of #3034

**Closed by jedwards4b** 2019-03-11 13:27 UTC
Labels: ty: Discussion, ty: enhancement
