### ISSUE TITLE
Build cprnc as part of create_test

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2457] opened 2018-04-12 11:00 UTC
It seems like the python implementation of cprnc (#1031 ) has stalled out (due to no fault of @mfdeakin-sandia 's -- we just hit some roadblocks with this, particularly related to netcdf dependencies). It occurred to me: The primary motivation for that python implementation was to avoid needing to maintain a build of cprnc on all of the systems we test on (users need to pre-build this on their system, we need to keep this up-to-date... which we're often not very good about... etc.).

Now that the cprnc build is more robust, can we simply build cprnc as part of each `create_test` instantiation? I feel that would make the Fortran version of cprnc a sustainable solution.

**Comment by jgfouca** [comment] 2018-04-12 17:17
@billsacks , that's a pretty good idea. What about users who want to use cprnc manually?

**Comment by rljacob** [comment] 2018-04-12 17:25
The bigger problem was you needed a build of cprnc for each fortran-netcdf combo on a system.  That's solved by having cprnc be a script that sets the environment for and calls just one combo.

**Comment by ekluzek** [comment] 2018-04-12 17:27
I agree with Jim. The standard build of cprnc should be used unless there isn't one available and then cprnc should be built. Note, that initial versions of CAM testing had as part of it a build of cprnc. This added complexity to the system, if the cprnc build failed, and people didn't know what to do.. And that happened often enough that it was an issue. So there was a purposeful choice to move to a system that didn't rebuild cprnc every time for standard systems. For systems that don't have cprnc built -- I do see adding the capability of building it as part of the system to make it easier to test on new systems. But, for standard systems I think it's better to have a version that's already built for everyone.

**Comment by billsacks** [comment] 2018-04-12 19:02
I don't feel strongly about this, so I don't want to spend too much energy arguing my point, but I do want to take one more stab at explaining myself.

First, the motivation: I realized that cprnc on hobart hadn't been updated in a long time, and so was marking tests as passed that should have failed (due to a change in dimension sizes of variables). This is definitely not the first time I have had something like this happen. I thought it would be nice if you could rely on the cprnc behavior being stable across machines.

Regarding @jgfouca 's point

> What about users who want to use cprnc manually?

I think this is a very good and important point: I do this a ton myself. I'd still imagine providing a cprnc build somewhere on the system, but automated tests wouldn't use that one.

Regarding @jedwards4b 's points:

> I think that we have some machines/compiler combinations which cprnc doesn't work with and we have a default build of cprnc on those systems that work for all compilers

I imagined we would only build cprnc once for a given create_test invocation, using the default compiler on that machine.

> I also don't like the added compiication of users having to debug cprnc every time they get a test failure. 

Sorry, I don't understand this point.

@rljacob - Sorry, I can't figure out if you're supporting my suggestion or saying it's unnecessary.

@ekluzek I think we can deal with this problem much better now:

> if the cprnc build failed, and people didn't know what to do.. And that happened often enough that it was an issue

we can put a build of cprnc in scripts_regression_tests (it only takes about 5 seconds) to ensure that it will always work on our standard test machines.

**Comment by ekluzek** [comment] 2018-04-12 22:04
@billsacks yeah, I would add a build of cprnc to scripts_regression_tests as it should have already been in there. Then it would be good to hear that a lot of people are running it and not finding any problems. That would be a good test case to show that adding it to create_test would be fine.

There is a valid point that if cprnc isn't built as part of create_test that the version being used will be out of date. And if there is an important feature missing in a new version of cprnc, that can be a problem with create_test. Essentially the current mechanism means that if you update cprnc -- you should create an issue that cprnc should be updated on standard machines. I don't think that step is happening now. And the builds of cprnc are probably happening sporadically. But, better tracking of when the builds are being done could show how off they are and indicate if a build as part of create_test would be better.

The last part of this though is how often does cprnc change in such a way that create_test needs the newer version? I suspect not so often...

**Comment by billsacks** [comment] 2018-04-13 01:47
> The last part of this though is how often does cprnc change in such a way that create_test needs the newer version? I suspect not so often...

But which is the cause and which is the effect? There are a few changes I've been wanting to make to cprnc for a while, but haven't because of (1) uncertainty about whether we are sticking with the fortran or moving to python, and (2) the pain involved in making any update, particularly one that requires coordination between cprnc code and scripts (as one of my changes does) -- since this involves synchronization across all cesm and e3sm test platforms.

**Comment by billsacks** [comment] 2018-05-02 20:14
From today's cime call: Feeling is that it could make sense to tackle this. I'll plan to take it at some point.

The main reason not to do this is if we'd be moving ahead with the python version of cprnc. @mfdeakin-sandia was close to having this working, though still needed to do more testing. But this would require having an installation of python's netcdf4 on the system. (See also #1031.) If we started building cprnc as part of the test system, as suggested in the current issue, then I wouldn't see much need for having a python version myself, and there are downsides to the python version, like performance and requiring a netcdf4-python installation. The main upside I see to the python version is that it allows tighter integration between cprnc and the rest of the test system. (I originally thought it would be easier to add new functionality in the python version, but I'm not sure that's really true: you have to be very careful about how you write things in order to maintain decent performance, so it can actually be harder in some ways.) We may wait to make a final call until we've had more discussions about what netcdf python library (if any) we'll allow as a cime dependency (we want something for ctsm, so cime can write netcdf parameter files, but the scipy netcdf would probably be sufficient there: we probably don't need netcdf4 support).

**Comment by jgfouca** [comment] 2018-08-08 22:54
Incorrect closing due to automatic github detection of something from e3sm.

**Closed** 2020-02-27 17:46 UTC
Labels: Assigned, tp: system tests, tp: tools, ty: enhancement
