### ISSUE TITLE
Cannot change RESUBMIT while model is running

### ISSUE THREAD

**Issue by golaz** [ESMCI/cime#3338] opened 2020-01-07 19:41 UTC
In one of my recent simulation, I tried to increase the number of automatic resubmissions using:

`./xmlchange -id RESUBMIT -val 6`

Unfortunately, when the next job started, it stopped with the following error:

`ERROR: File /compyfs/gola749/E3SM_simulations/20191216.alpha20.piControl.ne30_r05_oECv3_ICG.compy/case_scripts/env_run.xml appears to have changed without a corresponding invalidation, modtimes 1577796971.00 != 1577892633.00 `

Resubmitting the job manually afterwards with

`./case.submit`

worked and the job ran.

**Comment by rljacob** [comment] 2020-01-07 19:42
I thought you can always edit env_run.xml without disrupting anything else in CIME.  Is that not true?

**Comment by jedwards4b** [comment] 2020-01-07 20:04
A feature implemented by @jgfouca - I think the issue is that there is an active object copy of env_run.xml in memory and writing to the file creates a discrepancy that is hard to reconcile.

**Comment by rljacob** [comment] 2020-01-07 20:34
So to avoid the error, he'd have to wait for the current resubmissions to finish and then make the change?

**Comment by jedwards4b** [comment] 2020-01-07 20:36
Yes, that's correct.

**Comment by golaz** [comment] 2020-01-07 22:24
That seems like an inconvenience for the user. It's makes it more difficult to manage long simulations.

**Comment by billsacks** [comment] 2020-01-07 22:32
In general, I really support what @jgfouca did to bring a bit more sanity and safety in the file locking. But I wonder if we should have a separate, very small file of variables that are safe to change in the midst of a run? I'm not sure what that would include other than `RESUBMIT`.... I'm also not sure if `RESUBMIT` is guaranteed to be safe to change in the midst of a run, but maybe it's a common enough desire to set that (and maybe a few other variables) that we can live with the small risk?

**Comment by billsacks** [comment] 2020-01-07 22:34
Issues would arise if a cime process is trying to modify this file at the same time as a user. So actually, `RESUBMIT` is not completely safe to modify when the case is running, because the case will automatically change this variable at the end of the run, and if you get unlucky and run your xmlchange command at that same time, then you're in trouble.

It's all a matter of balancing risk vs. convenience....

**Comment by ekluzek** [comment] 2020-01-07 22:43
The other way to do this would be to have the error show up when the xmlchange command was attempted -- rather than when the next submission happens. I'd rather see..

./xmlchange RESUBMIT=6

and have it tell me "You can't do that you idiot! You are currently running a simulation, and you can't change it until it finishes all of it's submissions. Or until you abort the current run. Idiot...", then have it abort the running simulation.

Would it be possible to have the error be reported in xmlchange? Or at least when check_case is run? I know that doesn't prevent you from hand editing the file, but you should expect problems then.

**Comment by golaz** [comment] 2020-01-07 23:32
Personally, I have never been a fan of CIME's philosophy of protecting "stupid users from themselves"... I'm an optimist and prefer to think that users can be educated and should be empowered.

I can think of many legitimate reasons for wanting to change RESUBMIT, STOP_N, REST_N and possibly others for the next automatic resubmission.

**Comment by jgfouca** [comment] 2020-01-08 00:47
@golaz , we are also protecting ourselves from from ourselves (cime developers). Prior to the additional error checking I put into the XML "database", it was extremely easy for CIME developers to introduce very subtle errors into CIME by changing XML files "behind-the-back" of the currently-running CIME process and then leaving the system in an inconsistent state.

See https://github.com/ESMCI/cime/issues/2161 for the full details of that discussion.

There is definitely room for improvement in the error handling. With a sentinel file, xmlchange could know that the CIME case was actively running and immediately reject any changes as @ekluzek suggested.

Also relevant is a comment from me in another issue:
```
One thing that might be easier is if we further breakdown the env XML files in such a way that we know it is safe to change values in file X during phase Y. For example, if we had env_submit.xml, we would know it's safe to change env_submit.xml values during case_run.
```

This has come up at least 3 times in the last year, so we should probably discuss during tomorrow's telecon.

**Comment by jonbob** [comment] 2020-01-08 15:09
For what it's worth, I agree with @golaz . E3SM is not a community project and is geared for users with a deeper understanding of the system. We need to provide capability for those users, not prioritize greater protection. I myself change RESUBMIT often during a run, depending on mid-run analysis, and find it very useful.

**Comment by billsacks** [comment] 2020-01-08 15:37
I respectfully disagree with the sentiments raised by @jonbob and @golaz . I suspect that even most of the software engineers who work on E3SM and CESM aren't aware of many of the scenarios in which you could accidentally shoot yourself in the foot, particularly before the recent protections @jgfouca has added -- let alone more casual users. Even if most people read the documentation (which I suspect most people do not), educating people on all of the possible ways to shoot yourself in the foot would be a massive undertaking. I feel it is easier and far more robust to have protections in the software implementation.

That said, I'm hopeful that we can find a compromise for variables that are commonly modified during a run. (I wonder if there would be a way to have an xmlchange of RESUBMIT register the request for a change in some auxiliary file, and then this is reconciled with the actual env_run.xml at the end of a currently ongoing run.... details would need to be worked out.)

**Comment by jonbob** [comment] 2020-01-08 15:43
Thanks @billsacks -- I know there are a range of opinions on this subject and always appreciate your input. I do need to point out that CESM and E3SM are being developed for different sets of users, so our priorities may diverge at times. I don't believe the systems have to agree on all aspects, and this may be one of those situations in which CIME could add different protections for the different user bases.

**Comment by jedwards4b** [comment] 2020-01-08 15:45
I think that this feature is too deeply embedded to treat separately according to CIME_MODEL.

**Comment by jonbob** [comment] 2020-01-08 15:47
That's unfortunate. Can it be reworked then? Or simply removed?

**Comment by jgfouca** [comment] 2020-01-08 18:18
I agree with @billsacks. I think we need to explore putting much more "smarts" into xmlchange (or somewhere else) to allow users to modify XML values and have these values take effect the next time a Case object is loaded without impacting any currently loaded Cases.

**Comment by jonbob** [comment] 2020-01-08 18:37
@jgfouca - can you revert this change until that support is added?

**Comment by rljacob** [comment] 2020-01-08 21:17
@jonbob have you been able to change RESUBMIT while a job is running without seeing the error message @golaz saw?   The code Jim added has been around for at least a year.

**Comment by jonbob** [comment] 2020-01-08 21:25
@rljacob - historically I have been able to. But not recently, as you said...

**Comment by billsacks** [comment] 2020-01-08 21:59
On the cime telecon a number of good ideas were floated. I will let others comment more on solutions they proposed, including what I think was the agreed-upon solution in the near-term, which was to provide a mechanism for bypassing these error checks by setting something like a `CIME_WIZARD` environment variable. (Am I remembering that right? Too much else has happened in the last hour.)

I do, however, want to make a note (for the record) of another idea I thought of on the telecon, because I think it holds some promise: The main problem seems to be that the xml files remain "locked" during the case.run process. While we generally want files to be locked during cime processes, we could provide an exception for the `case_run` function (or possibly just during the actual model run piece of this), allowing variables to be changed by other processes while the model is running. To do this, we would need to flush the case before running the executable, then reload it afterwards.

The issue (which @jgfouca pointed out) would be that any local variables set from the case before the run would potentially be invalid after the run. We (cime developers) would need to be careful to reload any such variables after the model run. This actually appears to be an issue currently for `POSTRUN_SCRIPT` and maybe a couple of other variables that are referenced in `case_run`: if those were changed via xmlchange commands during a run, there would be problems. Other than those handful of variables in `case_run` itself, the need to be careful about reloading variables wouldn't be a large burden for normal model runs, since the case.run script exits after `case_run`. This would be a bigger pain for testing, but my feeling is that it's okay to assume that the user isn't messing with a test case in the midst of a test run.

**Comment by jgfouca** [comment] 2020-01-08 22:04
Thanks, @billsacks. That captures the issue nicely. I'll try to have PR soon.

**Comment by golaz** [comment] 2020-01-09 00:04
@billsacks and @jgfouca : thanks for trying to come up with a constructive solution to this problem. I appreciate your efforts.

Just in case, I was just thinking about a possible workaround: 

```
cp -a env_run.xml env_run.xml.keep
./xmlchange -id RESUBMIT -val 6
touch env_run.xml --reference env_run.xml.keep
```

I haven't tried this to verify if it is sufficient to fool CIME. But we can probably all agree that this is not the most desirable option.

**Comment by jedwards4b** [comment] 2020-01-09 01:52
@golaz I think that what may happen in this case is that your change to env_run.xml will be overwritten when the job is resubmited and the new env_run.xml will have the original RESUBMIT-1

**Comment by golaz** [comment] 2020-07-11 02:07
I'm going to have bring this up again unfortunately. This is currently not working (again, still?) or I just don't understand why it was designed the way it was. Here is the scenario. 

I have a long control simulation that is currently running. Turns out the simulation looks better than anticipated and I decide it is worth extending beyond my original plan. While the last segment is running:

```
./xmlquery RESUBMIT
	RESUBMIT: 0
```

So I increase the number of RESUBMIT

```
./xmlchange -file env_run.xml -id RESUBMIT -val 5
./xmlquery RESUBMIT
	RESUBMIT: 5
```
However, when the current job finishes, the simulation stops completely with no job being resubmitted. 

So instead I need to manually issue

`./case.submit`

to get the job going instead.

Could someone clarify whether this is how this CIME feature is intended to work or whether that's a bug?

**Comment by jgfouca** [comment] 2020-07-11 21:52
@golaz, the fix I put in a while back removed the modtimes error check that you demonstrated when you originally filed this ticket. This will at least keep the current CIME instance from crashing when you ./xmlchange something while it's running.

Unfortunately, this didn't really address the core issue which is that CIME has multiple levels of caching going on when it comes to the XML env values. I'll copy some relevant comments from #2161  :

```
That brings me to my next concern: the weak guarantees offered by the CIME data model (by that I mean the database of env XML values for a case). The value for an XML entry id for an active CIME process exists in at least 3 places:

1) storage in a local variable, e.g. `foo = case.get_value("FOO")`
2) The special entry-id cache in EnvBase
3) The in-memory XML representation in GenericXML
4) The value it has on-disk in its XML file

As a rough analogy, think of (1) as a CPU register, (2) as a CPU cache, (3) as main memory, and (4) as disk. All these things need to be coherent or things will get very weird fast, and the same is true for CIME.
```

@golaz , one way to support the RESUBMIT trick you're trying to do is to go back to the old days when CIME consisted of shell scripts that used xmlquery every time they wanted an env value for a case. This approach is the reason that simple CIME scripts back then took multiple minutes to complete and now they take just a few seconds.

Another approach is to manage env values through a database instead of XML files. This would be a very dramatic, non-backwards compatible, change to CIME that we've avoided looking at. It's possible that we just need to bite the bullet and do it since we keep running into this issue and can't think of any other way to achieve both coherence and performance on all env entries.

Another approach, perhaps less disruptive, is to allow a limited number of "volatile" env entries that users might want to change while a CIME instance is running. Volatile entries would have all caching disabled, which would make them slow to read/write, but we could perhaps tolerate this performance penalty if it was for a very limited set of values. I think @billsacks originally had this idea. @jedwards4b @WesCoomber @rljacob and @mvertens may have thoughts on this too. @golaz and @jonbob would probably have a good idea of which set of env values needs to be volatile.

So, to answer your question: yes, the behavior you saw is expected and modern CIME was designed this way intentionally in order to improve performance and stability.

CIME developers, we really need to put this issue behind us. I will lead this effort if that's OK.

**Comment by golaz** [comment] 2020-07-14 18:58
@jgfouca : thanks for the explanation. The analogy with caching levels makes a lot of sense.

Having a limited number of "volatile" variables would be useful and would probably be the least disruptive solution to implement. Replacing XML with a database would be a lot of work and require a lot of education on the user side; probably not worth it.

Some variables that come to mind would be:

```
CONTINUE_RUN
RESUBMIT
STOP_N
REST_N 
```

Those would probably take care of 98% of my use cases.

**Comment by mnlevy1981** [comment] 2020-08-19 15:40
I wanted to chime in to say that I was able to change `RESUBMIT` in a CESM case (using `cime5.8.28`) while the model was running -- I did this just last week. I have the short-term archiver on, and I believe it is the archiver that actually re-submits the job when `DOUT_S = TRUE`, so my theory based on this thread is that I would not have been able to change `RESUBMIT` on the fly if the archiver was turned off. Does that sound plausible?

**Comment by jedwards4b** [comment] 2020-08-19 15:46
@mnlevy1981 it is plausable - if the python object code which is going to use that variable is not in memory when you make the change then there won't be any error.  This could be because the model is in the queue or because you have DOUT_S=TRUE and you change the value while the model and not the archiver is running.

**Comment by jgfouca** [comment] 2020-08-25 00:46
@golaz, I'm looking at this issue now. The situation is extremely subtle, so I think the more precise we can be about the requirements, the better chance we have at getting an acceptable solution. @billsacks and @jedwards4b , feel free to chime in here as well.

Let's get a current lay of the land. As far as I can tell, the only potentially long-running case phase in CIME would be case.run. There is also a potentially long wait between case.submit and case.run, in the case where the queue is busy, but there's no active CIME process during this wait. If the user makes changes between case.submit and when case.run actually starts running, I think things should work just fine; please correct me if I'm wrong. This means we can focus on the case where case.run is currently busy running a long simulation and the user wants to change something.

Looking at your list:
CONTINUE_RUN
RESUBMIT  (we probably want DOUT_S too, otherwise it may not be possible to enable resubmit)
STOP_N
REST_N

I assume RESUBMIT is the only one that actually needs to impact the current running instance CIME. This is because, in case_run.py, we have this code that runs after the model is done:
```
    resubmit_num = case.get_value("RESUBMIT")
    resubmit = False
    if not dout_s and resubmit_num > 0:
        resubmit = True
   ...
    if resubmit:
        job = case.get_primary_job()
        case.submit(job=job, resubmit=True)
```

So, this code would need to see user changes to RESUBMIT in order to work the way you want it to work.

As for the other values, I assume they all just need to apply to the subsequent, not current, run.

Unfortunately, case_run/case_submit seem to want to make changes to CONTINUE_RUN, both before and after the model run. So it could be very difficult to sanely handle this value if the user is also allowed to make changes to this value via xmlchange. If the both the user and CIME make concurrent changes to a value, how should CIME resolve this? @billsacks , @jedwards4b , maybe you can help me here, the situation with CONTINUE_RUN is so muddled. case_run has several places where it sets CONTINUE_RUN to RESUBMIT_SETS_CONTINUE_RUN. There's also a place in case_submit.py which checks RESUBMIT_SETS_CONTINUE_RUN before setting CONTINUE_RUN to True. The latter at least makes a little sense to me, since it would allow the user to have control over CONTINUE_RUN if RESUBMIT_SETS_CONTINUE_RUN was False; the behavior of CONTINUE_RUN/RESUBMIT_SETS_CONTINUE_RUN in case_run.py makes no sense at all to me.

I propose we move both RESUBMIT, CONTINUE_RUN, and RESUBMIT_SETS_CONTINUE_RUN to a new env_volatile.xml file. Doing a get_value for these values would always check the modification date of the file before returning a value. If the modification date looks newer than the last time it was checked, the file would be re-read.

**Comment by billsacks** [comment] 2020-08-25 13:18
@jgfouca thanks for your extensive thoughts on this. I'm not very familiar with the details of these CONTINUE_RUN-related variables, so I can't comment on that. Your overall plan sounds fine if you think it will work. Would this still allow the user to change other variables (like `STOP_N`) in the middle of the run and have them take effect in the next run?

Your point about this mainly being a problem during case_run leads me to echo some thoughts I had earlier (https://github.com/ESMCI/cime/issues/3338#issuecomment-572277432): Would we be able to solve this issue for 99% or more of cases if we flushed the case right before launching the executable and then reloaded it after the executable returned? It feels like this has some pros and cons relative to the "volatile" idea?
- Pros:
  - Don't need to decide which variables should be volatile: all variables will be treated equally
  - Don't need to add code to handle these volatile variables
- Cons:
  - Only handles the problem during the model execution, not rare cases where someone is trying to do this at some other time
  - Requires some care in the case_run function: need to reset any local variables after the model execution that may have been invalidated by the reload

Either solution seems okay to me, so if you have a feeling as to which will be better (for the user, to implement, maintain, etc.), I'm fine going with your choice.

**Comment by mnlevy1981** [comment] 2020-08-25 14:47
> * Pros:
> 
>   * Don't need to decide which variables should be volatile: all variables will be treated equally

This seems like a pretty big pro to me. I could see arguments for being able to change the value of some of the variables in `env_batch.xml` mid-run (this job sat in the queue for ever, so when CIME resubmits it I'd like `JOB_QUEUE` to point to a better queue; I increased `STOP_N` for the next run, so I need to increase `JOB_WALLCLOCK_TIME` as well) and I bet the more people you talk to, the larger the list of variables in `env_volatile.xml` will get.

**Comment by golaz** [comment] 2020-08-25 16:24
@jgfouca and @billsacks : thanks for carefully considering options here. The details on how CIME works are nebulous to me, so I cannot really comment on the pros and cons of the proposed options. It seems to me like both options would solve the problem at hand. I do agree with @mnlevy1981's comment above that over time there is a risk of requests for more and more variables to be included in the `env_volatile.xml` which might defeat the original purpose of caching. But I'll leave it to you CIME experts to decide on the better course to take.

**Comment by jgfouca** [comment] 2020-08-25 16:51
@billsacks,

> Would this still allow the user to change other variables (like STOP_N) in the middle of the run and have them take effect in the next run?

Yes. I think setting up things for the next run is generally a lot easier than trying to allow the user to impact the current running process. The only issue here is that you don't want to overwrite their changes when the current CIME process is closing itself, so I will likely restore the timestamp check once volatiles are implemented.

**Comment by jgfouca** [comment] 2020-08-25 16:53
@billsacks , I will look into your idea of just reloading all of CIME after the executable is done, that seems like a pretty good idea.

**Comment by billsacks** [comment] 2020-08-25 16:59
Okay, either way: I was imagining that handling user's changes in variables not in env_volatile.xml would still be tricky, due to this point:

> The only issue here is that you don't want to overwrite their changes when the current CIME process is closing itself

but if that's not too hard to work around, then it seems like my Pro may not apply:

> Don't need to decide which variables should be volatile: all variables will be treated equally

**Comment by jedwards4b** [comment] 2020-08-25 17:02
But if the case is flushed prior to starting the model and reloaded upon completion then it seems that there would be no need to check consistency at the point of reloading - the file contains the correct values.  There is no way that I can think of that what is in memory could be updated after the flush.   Am I missing something?

**Comment by jgfouca** [comment] 2020-08-25 17:06
@jedwards4b, everything would be OK except for local variables.

**Comment by billsacks** [comment] 2020-08-25 17:08
> But if the case is flushed prior to starting the model and reloaded upon completion then it seems that there would be no need to check consistency at the point of reloading - the file contains the correct values. There is no way that I can think of that what is in memory could be updated after the flush. Am I missing something?

Are you referring to this point?:

> Requires some care in the case_run function: need to reset any local variables after the model execution that may have been invalidated by the reload

If so, what I was referring to was local variables like this (this may be the only current example):

https://github.com/ESMCI/cime/blob/503d6c56889fe84c04369f6810993280f77d5ab6/scripts/lib/CIME/case/case_run.py#L289

The local variable `postrun_script` is set before running the model but referenced afterwards. In this case, I think we could just move the setting of `postrun_script` to later.

**Comment by jgfouca** [comment] 2020-08-25 17:25
@billsacks , yep, that's exactly what I did.

**Closed** 2020-08-28 19:25 UTC
Labels: CRITICAL, tp: CIMElib, ty: Discussion
