### ISSUE TITLE
--generate flag affects success of test build?

### ISSUE THREAD

**Issue by mnlevy1981** [ESMCI/cime#1699] opened 2017-06-19 17:40 UTC
This is a weird issue and I'm not 100% sure it's something in CIME, but the problem seems to be reproducible and the only change is in the `create_test` call... if I run

```
$ ./create_test --xml-machine hobart \
                --xml-compiler nag \
                --xml-category aux_pop_MARBL \
                --test-root /home/mlevy/work/tests/aux_pop_MARBL/cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49_002.pgi \
                --compiler pgi
```

Out of a sandbox that is basically what is being tested as `cesm2_0_alpha06o` but swapping the POP trunk out in favor of a branch for MARBL development, then the eight tests in `aux_pop_MARBL` all run successfully.

However, if I run

```
./create_test --xml-machine hobart \
              --xml-compiler nag \
              --xml-category aux_pop_MARBL \
              --test-root /home/mlevy/work/tests/aux_pop_MARBL/cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49.pgi \
              --compiler pgi \
              --baseline-root /home/mlevy/work/baselines/aux_pop_MARBL \
              --generate cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49
```

Then two of the eight tests fail to build:

```
Finished MODEL_BUILD for test SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7 in 48.248959 seconds (FAIL). [COMPLETED 1 of 8]
        ERROR: BUILD FAIL: ocn.buildlib failed, cat /scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/bld/ocn.bldlog.170619-103750
Finished MODEL_BUILD for test SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_ladjust_bury_coeff in 28.986746 seconds (FAIL). [COMPLETED 3 of 8]
        ERROR: BUILD FAIL: ocn.buildlib failed, cat /scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_ladjust_bury_coeff.G.20170619_102001_ip9uqt/bld/ocn.bldlog.170619-103915
```

The compiler error in the build log is not very useful:

```
mpif90  -c -I. -I/scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/bld/pgi/mvapich2/nodebug/nothreads/include -I/scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/bld/pgi/mvapich2/nodebug/nothreads/mct/noesmf/c1a1l1i1o1r1g1w1e1/include -I/usr/local/netcdf-pgi/include -I/usr/mpi/pgi/mvapich2-2.1-qlc/include -I/cluster/pnetcdf-1.6.1-pgi-pgcc-pgf-15.1-mvapich2-2.2rc1/include -I/scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/bld/pgi/mvapich2/nodebug/nothreads/include -I/home/mlevy/codes/CESM/cesm2_0_beta06+marbl_dev/cime/scripts/Tools/../../src/share/util -I/home/mlevy/codes/CESM/cesm2_0_beta06+marbl_dev/cime/scripts/Tools/../../src/share/include -I/home/mlevy/codes/CESM/cesm2_0_beta06+marbl_dev/cime/scripts/Tools/../../src/share/RandNum/include -I/scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/bld/lnd/obj -I. -I/scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/bld/ocn/source -I/scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/bld/lib/include -i4 -gopt  -time -Mextend -byteswapio -Mflushz -Kieee    -O0  -DCCSMCOUPLED -DMARBL_TIMING_OPT=CIME -DBLCKX=25 -DBLCKY=20 -DMXBLCKS=1 -DZERO_SEA_ICE_REF_SAL  -DTAVG_R8  -DNT=35 -DECOSYS_BASE_NT=32 -DMARBL_NT=32 -DZOOPLANKTON_CNT=1 -DAUTOTROPH_CNT=3 -DGRAZER_PREY_CNT=3 -DIRF_NT=0  -DNDEBUG -DHAVE_MPI  -DLINUX   -D_USE_FLOW_CONTROL   -DFORTRANUNDERSCORE -DNO_SHR_VMATH -DNO_R16  -DCPRPGI  -DHAVE_SLASHPROC -Mfree  -DUSE_CONTIGUOUS= /scratch/cluster/mlevy/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/bld/ocn/source/marbl_parms.F90
/home/mlevy/work/tests/aux_pop_MARBL/cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49.pgi/SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7.G.20170619_102001_ip9uqt/Tools/Makefile:788: recipe for target 'marbl_parms.o' failed
```

But the same file compiles successfully in the six other tests (as well as all eight tests when I'm not generating baselines)

Has anyone else run into this sort of issue? My first thought was that it was a PGI compiler bug because (a) the test suite runs fine with NAG and Intel compilers, even if I'm generating baselines, and (b) most issues with PGI seem to be compiler bugs... but the fact that sometimes the compiler is okay with `marbl_parms.F90` and sometimes not makes me wonder if something else is going on. Maybe the order the tests are built in changes when generating baselines?

@rljacob I have no idea how to label this issue -- it might be a machine issue (we only have PGI 17.4 / 17.5 available on hobart), it might be CESM-only, it might be a scripts issue, it might be a testing issue, it's probably low priority because we don't really depend on PGI, etc etc.

**Comment by jedwards4b** [comment] 2017-06-19 18:32
I cannot reproduce your case from the latest code. 
 Missing testmod file '/home/jedwards/cesm2_0_alpha/cime/../components/pop/cime_config/testdefs/testmods_dirs/pop/ecosys_read_fallback_gx3v7'

**Comment by mnlevy1981** [comment] 2017-06-19 18:47
From components/pop run

```
$ svn switch https://svn-ccsm-models.cgd.ucar.edu/pop2/branch_tags/marbl_dev_tags/marbl_dev_n49_cesm_pop_2_1_20170601/
```

And you don't need to run the full test suite, I reproduced the build error with

```
./create_test SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_ladjust_bury_coeff \
              SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7 \
              --test-root /home/mlevy/work/tests/aux_pop_MARBL/cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49_rerun \
              --baseline-root /home/mlevy/work/baselines/aux_pop_MARBL \
              --generate cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49
```

**Comment by mnlevy1981** [comment] 2017-06-19 19:00
The following source mod

```
$ svn diff
Index: marbl_parms.F90
===================================================================
--- marbl_parms.F90     (revision 85756)
+++ marbl_parms.F90     (working copy)
@@ -26,7 +26,7 @@
   use marbl_constants_mod, only : c2
   use marbl_constants_mod, only : c1000
   use marbl_constants_mod, only : dps
-  use marbl_constants_mod, only : molw_Fe
+!  use marbl_constants_mod, only : molw_Fe
 
   use marbl_internal_types, only : autotroph_parms_type
   use marbl_internal_types, only : zooplankton_parms_type
@@ -127,7 +127,7 @@
   ! dust remin gDust = 0.035 gFe       mol Fe     1e9 nmolFe
   !                    --------- *  ----------- * ----------
   !                      gDust      molw_Fe gFe      molFe
-  real(kind=r8), parameter :: dust_to_Fe = 0.035_r8 / molw_Fe * 1.0e9_r8
+  real(kind=r8), parameter :: dust_to_Fe = 0.035_r8 / 55.845_r8 * 1.0e9_r8
 
   ! parameters related to Iron binding ligands
   integer (int_kind), parameter :: Lig_cnt = 1 ! valid values are 1 or 2
```

Seems to fix the issue, so I guess I'm back to believing it's a PGI compiler bug? But why is it only triggered with `--generate`?

**Comment by mnlevy1981** [comment] 2017-06-19 19:40
(Without the POP source mod, the `--compare` flag causes the test to fail as well)

**Comment by jedwards4b** [comment] 2017-06-19 20:05
This test works fine for me: 
 ./create_test SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_ladjust_bury_coeff SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7 --baseline-root /scratch/cluster/jedwards/marbl --generate marbl 
The error indicates that perhaps a Makefile dependency is incorrect and marbl_parms is being compiled prior to marbl_constants_mod

**Comment by mnlevy1981** [comment] 2017-06-19 20:58
I was able to run the tests out of your sandbox in

```
/home/jedwards/cesm2_0_alpha/cime
```

but still get failures in my sandbox. So it's not something in my environment, it really is in my sandbox.

It looks like you are using the latest CIME master instead of the alpha.23 tag, but it also looks like the only CIME differences are in documentation... so I'm really confused about what's going on. My sandbox uses PGI 17.05 instead of 17.04, but had been seeing the error with both versions so that's probably not it.

Weird.

**Comment by billsacks** [comment] 2017-06-21 16:23
I think this has to do with the exact length of the case name rather than whether `--generate` is included. I ran these three tests:

(1) With `--generate`

```
./create_test SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_ladjust_bury_coeff \
              SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7 \
              --test-root /home/sacks/work/tests/aux_pop_MARBL/cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49_rerun \
              --baseline-root /home/sacks/work/baselines/aux_pop_MARBL \
              --generate cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49
```

Build failed.

(2) Without `--generate`

```
./create_test SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_ladjust_bury_coeff \
              SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7 \
              --test-root /home/sacks/work/tests/aux_pop_MARBL/cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49_nogen
```

Build passed

(3) Without `--generate`, but forcing the case name's length to be exactly the same as in (1):

```
./create_test SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_ladjust_bury_coeff \
              SMS.T62_g37.C1850ECO.hobart_pgi.pop-ecosys_read_fallback_gx3v7 \
              --test-root /home/sacks/work/tests/aux_pop_MARBL/cime5.3.0-alpha.28-cice5_20170609-marbl_dev_n49_nogen \
              -t G_20170621_100333_c6bjqh
```

Build failed.

I'm inclined to chalk this up to pgi weirdness and close this issue. @mnlevy1981 does that sound good?

**Comment by billsacks** [comment] 2017-06-21 16:24
Oh, and my tests were with

```
cime                               https://github.com/CESM-Development/cime/tags/cime5.3.0-alpha.28
cime_config                        https://github.com/CESM-Development/cime_config/tags/cime_config0.0.1.alpha.13/
components/cice                    https://svn-ccsm-models.cgd.ucar.edu/cice/trunk_tags/cice5_20170516
#components/pop                     https://svn-ccsm-models.cgd.ucar.edu/pop2/trunk_tags/cesm_pop_2_1_20170609
components/ww3                     https://svn-ccsm-models.cgd.ucar.edu/ww3/trunk_tags/ww3_170516
```

with POP at `https://svn-ccsm-models.cgd.ucar.edu/pop2/branch_tags/marbl_dev_tags/marbl_dev_n49_cesm_pop_2_1_20170601`

**Comment by mnlevy1981** [comment] 2017-06-21 18:15
@billsacks Before closing the ticket, can you see if the problem goes away with the SourceMod I mentioned [on the 19th](https://github.com/ESMCI/cime/issues/1699#issuecomment-309534887)? I'm willing to believe the case name length plays a role in this, but I don't think it's the only factor.

**Comment by billsacks** [comment] 2017-06-22 22:18
Yes, implementing that code change got the build to pass with something very similar to case (3):

> (3) Without --generate, but forcing the case name's length to be exactly the same as in (1):

(I had to use a different case name for this one, but was careful to use the same length case name.)

So I agree that it seems to be a combination of case name length and the factor involved with that SourceMod.

Okay to close this now?

**Closed** 2017-06-23 15:53 UTC
