### ISSUE TITLE
Request for test names with mods to not require machine/compiler strings 

### ISSUE THREAD

**Issue by ndkeen** [ESMCI/cime#2107] opened 2017-12-04 22:09 UTC
I posted as E3SM issue, but Jim F suggested I post here.

For example, these two tests:

```
ERS.f19_g16.I1850CNECACNTBC.cori-knl_gnu.clm-eca
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.cori-knl_intel18.cam-cosplite_nhtfrq5

would be better if it were:

ERS.f19_g16.I1850CNECACNTBC.clm-eca
SMS_D_Ln5.ne4_ne4.FC5AV1C-L.cam-cosplite_nhtfrq5

cori07% ./create_test ERS.f19_g16.I1850CNECACNTBC.clm-eca --machine=cori-knl
ERROR: Expected 4th item of 'ERS.f19_g16.I1850CNECACNTBC.clm-eca' ('clm-eca') to be in form machine_compiler
```

If a test is not using any xml mods (i.e. ERS.f19_g16.I1850CNECACNTBC.cori-knl_gnu) then one can simply run a test by ./create_test ERS.f19_g16.I1850CNECACNTBC (i.e. no need to specify machine + compiler option). But, if a test is using test mod (ERS.f19_g16.I1850CNECACNTBC.cori-knl_gnu.clm-eca), then one needs to specify the full test name 

`./create_test ERS.f19_g16.I1850CNECACNTBC.cori-knl_gnu.clm-eca`

**Comment by jgfouca** [comment] 2017-12-04 23:29
@jedwards4b , how hard would be it to change test names to be:

TYPE.GRID.COMPET.[TESTMOD].machine_compiler

?

**Comment by jedwards4b** [comment] 2017-12-04 23:50
It would require a lot of changes to the cesm testlist xml files unless it could somehow be made backward compatible.   @billsacks had some ideas regarding testlists, Bill?

**Comment by billsacks** [comment] 2017-12-05 02:39
@jedwards4b I did have some ideas regarding testlists, but they were pretty orthogonal to this discussion: My ideas revolve around having the full test name listed as a single string, using whatever format of testname string we use.

@jgfouca I don't understand your proposal: if someone specifies a test like `SMS.f09_g16.B1850.foo_bar`, how does the test system know if that's a test with the testmod directory `foo_bar` vs. a test with no testmod running on machine `foo`, compiler `bar`? I suppose it could try one and, if that doesn't work, then try the other. But that hardly leaves me feeling warm and fuzzy.

I thought @gold2718 had a good suggestion when he and I discussed this recently: He suggested having a string format that allows order to not matter – e.g., something like `t%SMS_D.g%f19_g17.c%B1850.m%cheyenne_intel.d%clm-eca` – which would be the same as `m%cheyenne_intel.g%f19_g17.t%SMS_D.c%B1850.d%clm-eca` (and many other orderings). (I wouldn't necessarily expect the test system to be smart enough to find the right baseline with reordering... though maybe it would, by normalizing the string into a particular order.) It seems like this would robustly solve the problem of optional components.

I agree with @jedwards4b that the hardest problem here is probably going to be backwards compatibility, which I think will at least be important for some period of time.

**Comment by jedwards4b** [comment] 2017-12-05 03:08
The problem is that we have two optional arguments machine_compiler and modifier and no way to tell the difference between them.   What if we required a double dot to indicate default machine?
That is ./create_test ERS.f19_g16.I1850CNECACNTBC..clm-eca?
But I already see that @ndkeen would not save anything in this case because cori-knl is not the default cori machine and gnu is not the default compiler so in this case his proposed change would save him nothing.

**Comment by billsacks** [comment] 2017-12-05 11:25
I like the idea of double dot. Or being more explicit, like using a machine_compiler of `default`.

**Comment by ekluzek** [comment] 2017-12-05 17:24
I prefer @billsacks suggestion of using a word like "default" to describe that it's a default machine/compiler.

**Comment by jgfouca** [comment] 2017-12-05 17:34
@billsacks , I think we could make CIME smart enough to recognize the difference. For example, this algorithm:

```
TEST.GRID.COMPSET.UNKNOWN
if UNKNOWN is in format X_Y and X is a known CIME machine and Y is a known compiler:
   treat unknown as MACHINE_COMPILER
else:
   treat unknown as a testmod
```

**Comment by jgfouca** [comment] 2017-12-05 17:37
The only problem would be if someone made a testmod with a name MACHINE_COMPILER.

**Comment by billsacks** [comment] 2017-12-05 18:13
@jgfouca yeah, I see your point. However, I like the other suggestions on the table better, because they are more extensible to other optional components that may be added to the test name in the future.

**Comment by jgfouca** [comment] 2017-12-05 19:22
@billsacks good point. I wasn't thinking of extensibility.

**Comment by jgfouca** [comment] 2018-01-04 21:28
Do we have an agreed-upon solution?

**Comment by billsacks** [comment] 2018-01-06 12:41
I'll second my own suggestion of using a special keyword for `machine_compiler` to support this use case. Based on @ekluzek 's points in #2197 , I wonder if something like `all` or `any` would make more sense than `default`. We might have to give some thought to the exact semantics, but I'm thinking something like:

1. If you're running this as a single test (`create_test TESTNAME`), it will run on the current machine with the default compiler

2. If this is defined in a text-based test list (`create_test` with the `-f` option), it will run on the current machine with all supported compilers (e.g., if there are three supported compilers on this machine, three tests will be run)

3. For CESM: If this is defined in an xml (or later, cfg)-based test list: If you're running without a `--compiler`/`--xml-compiler` option, it runs on the current machine on all supported compilers. If you're running with a `--compiler`/`--xml-compiler` option, it runs on the current machine with the specified compiler.

I realize this may be getting more complex than the original issue warrants, so we could move some of this functionality to a separate issue.

**Comment by jgfouca** [comment] 2023-08-21 16:13
Reopening because I think resolving this issue would add value. That said, changing the test case name format scares me because there are probably assumptions all over the code about its current form.

**Comment by jedwards4b** [comment] 2023-08-21 16:16
What if we added something like SMS.f19_g17.A.*_*.cam-outfrq9s   where * in this case means default?

**Closed** 2023-08-21 20:03 UTC
Labels: ty: Discussion, Assigned

**Comment by rljacob** [comment] 2023-09-21 21:15
I thought that create_test had an argument called something like --test-mods-dirs where you would specify the full path to the test mod but its not in the --help output.  Did I imagine that?

**Comment by jedwards4b** [comment] 2023-09-21 21:19
It does not - ./create_newcase has a --user-mods-dir
