### ISSUE TITLE
PR #2260 has caused some cime_developer tests to fail on anlworkstation during phase SETUP

### ISSUE THREAD

**Issue by dqwu** [ESMCI/cime#2263] opened 2018-01-30 16:46 UTC
The errors can be reproduced on anlworkstation by running a single cime_developer test:
`./create_test SMS.T42_T42.S --machine=anlworkstation --test-root=****`

Errors were:
```
        Traceback (most recent call last):
          File "./case.setup", line 58, in <module>
            _main_func(__doc__)
          File "./case.setup", line 55, in _main_func
            case_setup(case, clean=clean, test_mode=test_mode, reset=reset)
          File "scripts/lib/CIME/case_setup.py", line 233, in case_setup
            run_and_log_case_status(functor, phase, caseroot=caseroot)
          File "scripts/lib/CIME/utils.py", line 1447, in run_and_log_case_status
            rv = func()
          File "scripts/lib/CIME/case_setup.py", line 227, in <lambda>
            functor = lambda: _case_setup_impl(case, caseroot, clean, test_mode, reset)
          File "scripts/lib/CIME/case_setup.py", line 97, in _case_setup_impl
            case.load_env()
          File "scripts/lib/CIME/case.py", line 1300, in load_env
            env_module.load_env(self)
          File "scripts/lib/CIME/XML/env_mach_specific.py", line 78, in load_env
            self._load_modules(modules_to_load, force_method=force_method)
          File "scripts/lib/CIME/XML/env_mach_specific.py", line 102, in _load_modules
            self._load_modules_generic(modules_to_load)
          File "scripts/lib/CIME/XML/env_mach_specific.py", line 295, in _load_modules_generic
            newenv[lastkey] += "\n" + line
        KeyError: None
```
Do we need some settings on anlworkstation to make it work?

**Comment by jedwards4b** [comment] 2018-01-30 17:35
THis is a duplicate of #2262

**Comment by jgfouca** [comment] 2018-01-30 17:57
@jedwards4b , I don't believe this is a duplicate. This is a failure in the main code path, not a test. I will investigate.

**Closed** 2018-01-30 19:33 UTC
Labels: ty: help wanted
