### ISSUE TITLE
Coupler history file hr2x problems for forecasts < 24 hours.

### ISSUE THREAD

**Issue by kdraeder** [ESMCI/cime#2831] opened 2018-10-06 14:05 UTC
The cpl.hr2x files have averaged fields in them, despite the names 
and (previous) documentation (CIME issue #2773, ESCOMP/cesm#71).
They are written out only daily, but that leads to incorrect results 
when the forecast is less than a day long, as during data assimilation 
runs with, for example, 6 hour forecasts.  Then the files are written
only at hour 24, not hours 6, 12, 18.
And the files contain data averaged over hours 18-24, not over the 
full day implied by the file names (and frequency): 
case.cpl.hr2x.yyyy-mm-dd-00000.nc
TOD was added to the filenames in an earlier commit
(CIME #2754).

**Comment by kdraeder** [comment] 2018-10-25 15:54
@jedwards4b @rljacob 
I believe that my fix is confusing the writing of other coupler aux hist files
having write frequencies higher than daily.
I haven't figured it out entirely, but thought that someone should know
sooner rather than later.  A symptom is that those files (ha2x1h*, ha2x3h)
have 0 times written to them.

**Comment by billsacks** [comment] 2018-10-25 17:12
@kdraeder remind me: was your fix just https://github.com/ESMCI/cime/pull/2832? I can't see how that one would possibly affect other aux hist files....

**Comment by kdraeder** [comment] 2018-10-25 18:32
I believe that by adding the TOD to the file names
I confused the mechanism for deciding whether
a call is "first_call", how to find an existing file, etc.
I'm still figuring it out.

**Comment by kdraeder** [comment] 2018-10-26 02:03
Some progress; I fixed the file names to which the data
should be written to use the end of the forecast, 
instead of the current time.  So all the right time slots
are written to the right files.
But all the fields are 0s.  
The caseroot is /gpfs/fs1/work/raeder/Exp/Debug_ha_no_times.
There are sourcemods with my file name fix.

**Comment by kdraeder** [comment] 2018-10-26 14:39
The overall problem is that data assimilation uses forecasts
shorter than a day, while the coding in seq_hist_mod.F90
and cime_comp_mod.F90 assumes runs of an integral number of days.
When creating the auxiliary coupler history files,
there's a complicated interplay between the length of the
run and the data frequencies on the files that determine
when the data for the files should be generated
and when the files should be written.
The files with average quanities, e.g. ha2x1d,
end up with data in them which is averaged
over a shorter period than implied in their names.
This can be fixed by the user in a postprocessing step,
but can lead to confusion.
See PR #2879

**Comment by billsacks** [comment] 2018-10-26 16:38
@kdraeder my understanding is that the problem actually came in with https://github.com/ESMCI/cime/pull/2782 -- is that your understanding, too?

**Comment by kdraeder** [comment] 2018-10-26 16:54
@billsacks #2782 was the first time I dealt with seq_hist_mod.F90
and it did have to do with file names, but it was a separate issue,
in my mind.  If you think they are related enough by the thread
of multi-instance data assimilation, feel free to link them somehow.

**Comment by billsacks** [comment] 2018-10-26 17:42
For the record: At our meeting, we clarified that neither of @kdraeder 's recent PRs broke anything new (as far as we can tell); the problem is just that #2832 was not a complete fix. @kdraeder is going to make some one-off fixes on a branch for his applications. I'm going to close this issue. @kdraeder feel free to open other issues if you feel there are still things that need to be resolved on master.

**Closed by billsacks** 2018-10-26 17:42 UTC
Labels: in progress, maint-5.6_bugfix, tp: drv mct, ty: Bug
