### ISSUE TITLE
Build requires a clean for build to re-compile updated source files when used with nuopc

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#3488] opened 2020-04-12 19:15 UTC
I'm finding this with cime5.8.17 for the case SMS_D_Vnuopc.f19_g17_r05.I2000Clm50SpMizGs.cheyenne_intel

If I make changes to mosart source files, it will redo the ROF library build and relink CESM. But, it won't re-compile the files that were changed. As such I have to clean the rof build every time I make a change to source.

Technically this is for my mizuRoute branch on my fork, but the changes are unrelated regarding mizuRoute and are small. I'll try to redo this with the latest cime master.

**Comment by billsacks** [comment] 2020-04-12 20:50
I believe this is a known feature of the cime build system. You don't need to do a full clean, but you do need to do something like:

```
./case.build --clean-depends lnd
```

-- substitute `lnd` with the component for which you want to regenerate the dependencies.

**Comment by billsacks** [comment] 2020-04-12 20:52
By the way, the above may not work for lnd in the maint5.6 branch: I remember there was #3286 , which was fixed on master, but I'm not sure if the issue was fixed on the maint5.6 branch.

**Comment by ekluzek** [comment] 2020-04-12 21:45
This isn't on maint-5.6, but only a few versions behind master. I tried doing the clean of depends and it still doesn't compile the updated files.

**Comment by billsacks** [comment] 2020-04-12 22:06
> I tried doing the clean of depends and it still doesn't compile the updated files.

I believe that would be a bug. Can you give a detailed set of instructions so others can reproduce the issue? Actually, if you haven't already, it would be good if you determine whether you can reproduce the problem with one of the standard CESM components first, to rule out the possibility that there is an issue specific to the buildlib of this new MizuRoute component. You should probably do this with MOSART or RTM, since the sharedlib build of CTSM works somewhat differently from the builds of the river components.

You could also see where the problem is by manually removing `Srcfiles` from the build directory of this component. Then rebuild. See if (1) the `Depends` file is regenerated for this component (it should be), and (2) if the new files are picked up in the build. The point of this is to see if the problem is that `--clean-depends` isn't working right (not finding the `Srcfiles` file to remove), or if the problem is that, even if `Srcfiles` is forced to be regenerated, the new files don't get built.

**Comment by jedwards4b** [comment] 2020-04-13 15:01
I'll take a look at this if you can reproduce on master.

**Comment by jedwards4b** [comment] 2020-04-22 16:07
@ekluzek did you determine if this could be reproduced on master?  Should it be closed?

**Comment by ekluzek** [comment] 2020-04-22 18:58
When I try master I get an unrelated problem as follows...

>             getattr(mod, subname)(*subargs)
>           File "/glade/work/erik/ctsm_mizuRoute/cime/src/drivers/nuopc/cime_config/buildnml", line 458, in buildnml
>             _create_drv_namelists(case, infile, confdir, nmlgen, files)
>           File "/glade/work/erik/ctsm_mizuRoute/cime/src/drivers/nuopc/cime_config/buildnml", line 244, in _create_drv_namelists
>             nmlgen.write_nuopc_config_file(nuopc_config_file, data_list_path=data_list_path, skip_comps=skip_comps)
>         TypeError: write_nuopc_config_file() got an unexpected keyword argument 'skip_comps'
> 

So I haven't been able to show that it's a problem on master yet...

**Comment by jedwards4b** [comment] 2020-04-22 19:00
Is your master up to date?  If it is please provide instructions to reproduce the problem, if it's not please try with the latest master.

**Comment by ekluzek** [comment] 2020-04-22 20:09
OK, I had to update CMEPS as well as cime. I do still see this behavior, but only for nuopc and NOT for a normal MCT case.

So what I did was the following:

``` cshell
qcmd -- ./create_test SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default -r . --queue premium --walltime 00:20:00
# After it run to completion I checked if the build would rebuild code that I touched...
touch ../../../components/mosart/src/cpl/nuopc/rof_comp_nuopc.F90
./case.build
```

What I see is that the above file I touched wasn't recompiled, the archive just happens over again...

> Command gmake complib -j 8 MODEL=mosart COMPLIB=/glade/scratch/erik/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58/bld/lib/librof.a -f /glade/work/erik/ctsm_mizuRoute/cime/scripts/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58/Tools/Makefile CIME_MODEL=cesm  compile_threaded=FALSE  USE_KOKKOS=FALSE CASEROOT="/glade/work/erik/ctsm_mizuRoute/cime/scripts/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58" CASETOOLS="/glade/work/erik/ctsm_mizuRoute/cime/scripts/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58/Tools" CIMEROOT="/glade/work/erik/ctsm_mizuRoute/cime" COMP_INTERFACE="nuopc" COMPILER="intel" DEBUG="TRUE" EXEROOT="/glade/scratch/erik/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58/bld" INCROOT="/glade/scratch/erik/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58/bld/lib/include" LIBROOT="/glade/scratch/erik/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58/bld/lib" MACH="cheyenne" MPILIB="mpt" NINST_VALUE="c1a1l1r1" OS="LINUX" PIO_VERSION="2" SHAREDLIBROOT="/glade/scratch/erik/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58/bld" SMP_PRESENT="FALSE" USE_ESMF_LIB="TRUE" USE_MOAB="FALSE" COMP_LND="clm" USE_TRILINOS="FALSE" USE_ALBANY="FALSE" USE_PETSC="FALSE"  completed with output ar rv /glade/scratch/erik/SMS_D_Vnuopc_P72x1.f19_g17.I2000Clm50SpGs.cheyenne_intel.mosart-default.20200422_133751_4l5v58/bld/lib/librof.a ensemble_driver.o esm.o esmApp.o esmFlds.o esmFldsExchange_cesm_mod.o esmFldsExchange_nems_mod.o esm_time_mod.o esm_utils_mod.o med.o med_constants_mod.o med_fraction_mod.o med_internalstate_mod.o med_io_mod.o med_kind_mod.o med_map_mod.o med_merge_mod.o med_methods_mod.o med_phases_aofluxes_mod.o med_phases_history_mod.o med_phases_ocnalb_mod.o med_phases_prep_atm_mod.o med_phases_prep_glc_mod.o med_phases_prep_ice_mod.o med_phases_prep_lnd_mod.o med_phases_prep_ocn_mod.o med_phases_prep_rof_mod.o med_phases_prep_wav_mod.o med_phases_profile_mod.o med_phases_restart_mod.o med_time_mod.o med_utils_mod.o t_driver_timers_mod.o util.o
> a - ensemble_driver.o
> a - esm.o
> a - esmApp.o
> a - esmFlds.o
>

**Comment by jedwards4b** [comment] 2020-04-22 20:17
@ekluzek I know what the problem is, I'll have a fix soon.

**Comment by jedwards4b** [comment] 2020-04-22 20:25
Moved to https://github.com/ESCOMP/CMEPS/issues/61

**Closed by jedwards4b** 2020-04-22 20:25 UTC

**Comment by jedwards4b** [comment] 2020-04-22 20:29
Now fixed on CMEPS master

**Comment by ekluzek** [comment] 2020-04-22 20:42
Yay! Works for me.
