### ISSUE TITLE
document testing

### ISSUE THREAD

**Issue by mvertens** [ESMCI/cime#1295] opened 2017-04-02 22:56 UTC
clearer documentation is needed in CIME regarding both the use of create_test AND the use of scripts-regressions-test. For the latter, it is not clear at all how to understand and fix failures.

**Comment by rljacob** [comment] 2017-04-03 00:45
This is a partly a duplicate of #1060

**Comment by billsacks** [comment] 2017-04-21 17:38
Currently documentation of unit testing (http://esmci.github.io/cime/doc/build/html/misc_tools/unit_testing.html) is under "Misc tools". To me it feels like it would fit better under "CIME User’s Guide Part 2: CIME internals, Porting, Testing and Use Cases". How do others feel about that?

**Comment by gold2718** [comment] 2017-04-21 17:47
I am in favor of the move. As long as CIME is monolithic (no 'optional' or 'external' pieces), I think there should be one place for documentation.

**Comment by rljacob** [comment] 2017-04-22 02:43
The "testing" in part 2 is a placeholder for documentation of create_test.   "Misc tools" is for everything in the cime/tools directory.

**Comment by rljacob** [comment] 2017-04-22 02:47
And everything in cime/tools is "optional" in the sense you don't need it for the core functioning of cime.

**Comment by mvertens** [comment] 2017-04-22 03:00
I think that unit testing belongs with testing in the documentation and
therefore should accompany the part 2 documentation.

**Comment by billsacks** [comment] 2017-04-22 11:29
@rljacob - I made a new section in Part 2 - after "Testing with create_test" I added "Fortran unit testing" - see http://esmci.github.io/cime/doc/build/html/users_guide/index.html#users-guide2 . My rationale was that unit testing is (or should be) no more of an "optional" tool than system testing is.

**Comment by rljacob** [comment] 2017-04-25 03:57
I agree unit testing should be encouraged. But "tools" is still for optional parts of CIME so if unit testing is now as crucial a part of CIME as the system tests, we should move tools/unit_testing somewhere else.  If its just for testing fortran, we should move it to "src".

**Comment by mvertens** [comment] 2017-04-25 04:00
That's an interesting and valid point. Lets discuss this at the Wednesday
meeting.

**Comment by jgfouca** [comment] 2017-05-04 23:29
Adding docs.

**Closed by jgfouca** 2017-05-04 23:29 UTC
Labels: documentation, ready
