### ISSUE TITLE
PRE.f45_g37_rx1.ADESP_TEST.cheyenne_intel broken

### ISSUE THREAD

**Issue by jedwards4b** [ESMCI/cime#1717] opened 2017-06-29 22:22 UTC
This test fails in the run phase on the current cime master, it's not clear why.
Similar test PRE.f45_g37_rx1.ADEST.cheyenne_intel passes

**Comment by gold2718** [comment] 2017-06-29 23:01
I think this is a duplicate of #1622.

**Closed by gold2718** 2017-06-29 23:01 UTC
Labels: st: duplicate, ty: Bug
