### ISSUE TITLE
Add .gitignore entries to ignore files placed in scripts

### ISSUE THREAD

**Issue by billsacks** [ESMCI/cime#2182] opened 2018-01-04 03:02 UTC
With the new git-based workflow for CESM (which we plan to adopt within the next few weeks), it's becoming important that we avoid having non-ignored unknown files present in cime, to the extent possible. (See details in https://github.com/NCAR/manage_externals/issues/51#issuecomment-355184032 , which documents a conversation between @mvertens @bandre-ucar and myself.)

The most common culprit here is case directories, which many users put under cime/scripts. Therefore, we'd like to propose adding entries to `.gitignore` that:

- Ignore everything in the `scripts` directory in a blanket ignore line

- Selectively un-ignore things we care about

@mvertens suggested doing the same for `scripts/tests`, where output from `scripts_regression_tests` is often placed.

What do others think about this? @jgfouca @rljacob @jedwards4b in particular?

**Comment by billsacks** [comment] 2018-01-04 03:04
I should mention: In doing some experimentation, I noticed a scenario where you can lose data with git, which gets potentially worse if you have a catch-all `.gitignore` file like what we're proposing for `cime/scripts`: If you have a file or directory in your working directory that is git-ignored, and then you checkout a branch where there is a file or directory with the same name that has been committed to the repository, then your ignored file will be overwritten in a non-recoverable manner (as far as I can tell). I haven't thought of a scenario where this is likely to be a problem in practice, but given enough time this may bite someone, sometime.

That said, I'm still in favor of adding this blanket gitignore for things under scripts, because it seems important to do so for our new CESM workflow.

**Comment by billsacks** [comment] 2018-01-04 03:17
@bandre-ucar just added (in the manage_externals issue referenced above):

> Given the potential for data loss, I think using git ignore should be rejected, and for cime we should just stop encouraging people to create tests and cases in cime/scripts. Maybe even make the default to the source root.

Just to make sure we're all on the same page: this potential data loss could occur even now, given our existing .gitignore files. It's just that the problem becomes worse if we cast a wider net in the .gitignore file.

That said: I personally like @bandre-ucar 's idea of changing the default location for cases, if users can stomach it. I like having my cases nested somewhere within my sandbox, but I'd be very happy with them going in either `$SRCROOT/cases/`, `$CIMEROOT/scripts/cases/` or something similar. Note that if they go under a `cases/` directory by default (or something similar), then we could easily git-ignore that `cases` directory.

**Comment by mvertens** [comment] 2018-01-04 03:26
@billsacks @bandre-ucar - Given our past experience with changing the
user's workflow along with E3SM's experience I would be very very hesitant
to change the workflow unless its absolutely necessary. If the risk is
small of loosing data - then I would err on the side of keeping the current
workflow. Its possible that there are scripts out there that create a case
in the $SCRIPTSROOT sandbox by default - and all potentially all those
would have to ben changed. It would be helpful to hear from some of the
CESM developers (@mlevy1981, @alperaltuntas, @gold2718, @cacraigucar,
@ekluzek, @dbail10, @apcraig) and see how they feel about this issue.

**Comment by gold2718** [comment] 2018-01-04 03:54
I never put anything in the sandbox (except bugs, lots of bugs) -- my case files are all put somewhere in a workspace (which varies depending on whether it is a test or an experiment).

I am on the side of using .gitignore sparingly and probably not to make up for any issue which really rests with the checkout tool.

I think that most users end up with case directories in their scripts directory because that is what happens if you do not use a full pathname. Adjusting should not be difficult (IMHO).

**Comment by apcraig** [comment] 2018-01-04 04:29
There is a long history of dropping cases directly into the scripts directory.  To not allow that now seems pretty bad.  I would also like to add that if the new process creates a bunch of problems when users add new directories or files in their sandbox, then the process is flawed.  I think people add notes, personal READMEs, small scripts, pre or post processing tools (scripts), cases, temporary test code, and copies (backups) of files to their sandbox all the time in all different places as part of development.  The process should not require a gitignore to ignore new temporary files or directories.  If it does, you are just asking for problems.

Having said all that, if we're stuck having to answer the question at hand, then I would say adding a cases directory under scripts that becomes the default location for cases and then adding that cases directory to gitignore by default would be my suggestion.   

But to reiterate again, and maybe I don't understand the new process.  But if the general rule is that all files added to a sandbox are going to be committed automatically by the process, then I think the process is fundamentally flawed.

**Comment by rljacob** [comment] 2018-01-04 05:20
What is this "checkout_externals" thing that needs this?   AFAIK, git operates happily with files that have not been staged or committed.  It ignores them except "git status" will tell you that they are there.

The solution here is to make your "checkout_externals" work more like git and do nothing with files/dirs not under git control.

**Comment by billsacks** [comment] 2018-01-04 12:47
@mvertens @gold2718 @apcraig @rljacob Thanks for your thoughts.

I'll be honest: I'm personally feeling stuck between a rock and a hard place right now, because I see the points on both sides of this.

To answer @rljacob 

> What is this "checkout_externals" thing that needs this?

`checkout_externals` (currently at https://github.com/NCAR/manage_externals) is a tool developed by @bandre-ucar @gold2718 (with input from others in CSEG) to act as a sort of package manager / replacement for svn externals for CESM. This addresses our need to pull together multiple repositories (some in git and some in svn) into a top-level git repository and to facilitate multi-component (and thus, in CESM, multi-repository) development.

To answer @apcraig 

> But if the general rule is that all files added to a sandbox are going to be committed automatically by the process, then I think the process is fundamentally flawed.

Sorry if I was unclear on this point. Temporary files would not be committed automatically, but they would need to be removed or moved out of the way before rerunning `checkout_externals`. (Rerunning `checkout_externals` is like running `svn update` from the root level of CESM.) You may respond that that's just as bad, and I'd say you have a valid point.

To answer both @rljacob and @apcraig - I started off feeling the same way you do: untracked files shouldn't get in the way. The issue that @bandre-ucar raised was this: Currently, `checkout_externals` does a careful job of ensuring that the full update of all components will succeed before updating anything: it has an "update everything or update nothing" rule. While untracked files _usually_ would not prevent an update, they do prevent an update in the situation where you're trying to checkout a git branch that has a committed file with the same name as an untracked file in your sandbox. So in this case, `checkout_externals` would bail part-way through, with some externals updated and some not. @bandre-ucar @mvertens and I felt that was bad.

However, after seeing your views (which echoed my original view), I'm coming back around to thinking that we should ignore untracked files, allowing for a small risk that `checkout_externals` would bail part-way through. It feels to me that the amount of pain that will cause will be much less than the amount of pain caused by not allowing untracked files.

@bandre-ucar and @mvertens - It seems like we could do the following: Allow `checkout_externals` to run if there are untracked files present (but still prevent it from running in the other cases that it checks). If a `git checkout` command fails, catch the error and abort with a message like this:

```
Failed to update [path]

To fix this problem, cd to [path], run:
[whatever git checkout command we were trying to run]
and fix any errors that are encountered.

Then rerun checkout_externals
```

**Comment by jedwards4b** [comment] 2018-01-04 13:11
I've read this thread and I don't understand what the issue is - what new problem is introduced that doesn't currently exist?   I don't see a good argument here for introducing any wide ranging .gitignore for cime.

**Comment by billsacks** [comment] 2018-01-04 13:37
@jedwards4b the new issue is due to the use of `checkout_externals` and how it does its initial checks. See https://github.com/NCAR/manage_externals/issues/51 for details.

**Comment by jedwards4b** [comment] 2018-01-04 15:07
Thanks I understand now.   I don't think that this is a cime issue - it is an error in manage_externals that must be corrected there.

**Comment by billsacks** [comment] 2018-01-05 12:24
Upon further discussion between @mvertens @bandre-ucar and myself - based on input on this thread - we've decided not to go with this solution. Those interested in following this issue can follow https://github.com/NCAR/manage_externals/issues/51 for more details.

**Closed** 2018-01-05 12:24 UTC
Labels: tp: unknown, ty: Discussion, ty: enhancement
