### ISSUE TITLE
Problem with unsupported grid for SOM

### ISSUE THREAD

**Issue by gold2718** [ESMCI/cime#2535] opened 2018-05-02 22:34 UTC
The following case:
```
./create_newcase --case /scratch/cluster/goldy/ADESP_f45_f45_mg37 --compset ADESP --res f45_f45_mg37 --run-unsupported
```
crashes in check_input_data.py with the error (at `case.submit` time):
```
Loading input file list: 'Buildconf/docn.input_data_list'
  Model docn missing file domain1 = '/fs/cgd/csm/inputdata/ocn/docn7/SOM/UNSET'
```
This works fine if you use `--res f19_f19` (there are defaults for FV 1 degree and 2 degree).

**Comment by rljacob** [comment] 2018-10-10 19:51
Telecon Q:   Is this grid supposed to be supported?   Or is the error showing up late or not clear?

**Comment by billsacks** [comment] 2018-10-10 19:51
If the problem is that the error should be more clear and earlier in the process, then this is connected to https://github.com/ESMCI/cime/issues/2836

**Comment by billsacks** [comment] 2021-11-20 21:09
@gold2718 - from talking with @mvertens about #2836 , which looks similar to this, she thinks this issue is likely gone with CDEPS, at least in this form. So I'm going to close this, but feel free to reopen if you feel there are still similar issues that need to be resolved with NUOPC/CMEPS/CDEPS. (This may also be similar to the issue we discussed at last Tuesday's CSEG meeting, raised by @mnlevy1981 .)

**Closed by billsacks** 2021-11-20 21:09 UTC
Labels: ty: Bug
