### ISSUE TITLE
shr_mct_sMatReaddnc fails trying to read "idmap" as a file

### ISSUE THREAD

**Issue by ekluzek** [ESMCI/cime#1075] opened 2017-01-29 21:37 UTC
The test SMS_D_Lm1_Mmpi-serial.CLM_USRDAT.I1PTCLM45.yellowstone_pgi.clm-USUMB works in cime5.2.0-alpha.9 (for clm in cesm2_0_beta05), but fails in cime5.2.0-alpha.14. Instead of assuming identity map it tries to read in the file "idmap" as follows....

(prep_lnd_init) : Initializing mapper_Fr2l
(seq_map_init_rcfile)  called for mapper_Fr2l initialization
  
(shr_mct_sMatPInitnc) Initializing SparseMatrixPlus
(shr_mct_sMatPInitnc) SmatP mapname idmap
(shr_mct_sMatPInitnc) SmatP maptype Y
(shr_mct_sMatReaddnc) reading mapping matrix data decomposed...
(shr_mct_sMatReaddnc) * file name                  : idmap
 ERROR: (shr_mct_sMatReaddnc)No such file or directory

Note, all maps for this case are identity maps as it's a single point case...

  atm2ice_fmapname: "idmap"
  atm2ice_fmaptype: "X"
  atm2ice_smapname: "idmap"
  atm2ice_smaptype: "X"
  atm2ice_vmapname: "idmap"
  atm2ice_vmaptype: "X"
  atm2lnd_fmapname: "idmap"
  atm2lnd_fmaptype: "X"
  atm2lnd_smapname: "idmap"
  atm2lnd_smaptype: "X"
  atm2ocn_fmapname: "idmap"
  atm2ocn_fmaptype: "X"
  atm2ocn_smapname: "idmap"
  atm2ocn_smaptype: "X"
  atm2ocn_vmapname: "idmap"
  atm2ocn_vmaptype: "X"
  atm2wav_smapname: "idmap"
  atm2wav_smaptype: "Y"
  glc2ice_rmapname: "idmap"
  glc2ice_rmaptype: "Y"
  glc2lnd_fmapname: "idmap"
  glc2lnd_fmaptype: "Y"
  glc2lnd_smapname: "idmap"
  glc2lnd_smaptype: "Y"
  glc2ocn_rmapname: "idmap"
  glc2ocn_rmaptype: "Y"
  ice2atm_fmapname: "idmap"
  ice2atm_fmaptype: "Y"
  ice2atm_smapname: "idmap"
  ice2atm_smaptype: "Y"
  ice2wav_smapname: "idmap"
  ice2wav_smaptype: "Y"
  lnd2atm_fmapname: "idmap"
  lnd2atm_fmaptype: "Y"
  lnd2atm_smapname: "idmap"
  lnd2atm_smaptype: "Y"
  lnd2glc_fmapname: "idmap"
  lnd2glc_fmaptype: "X"
  lnd2glc_smapname: "idmap"
  lnd2glc_smaptype: "X"
  lnd2rof_fmapname: "idmap"
  lnd2rof_fmaptype: "X"
  ocn2atm_fmapname: "idmap"
  ocn2atm_fmaptype: "Y"
  ocn2atm_smapname: "idmap"
  ocn2atm_smaptype: "Y"
  ocn2wav_smapname: "idmap"
  ocn2wav_smaptype: "Y"
  rof2lnd_fmapname: "idmap"
  rof2lnd_fmaptype: "Y"
  rof2ocn_fmapname: "idmap"
  rof2ocn_fmaptype: "Y"
  rof2ocn_ice_rmapname: "idmap"
  rof2ocn_ice_rmaptype: "Y"
  rof2ocn_liq_rmapname: "idmap"
  rof2ocn_liq_rmaptype: "Y"
  wav2ocn_smapname: "idmap"
  wav2ocn_smaptype: "X"

@billsacks @bandre-ucar @mvertens

**Comment by mvertens** [comment] 2017-01-29 22:28
Could you please assign this to me. I think this will be an easy fix.

**Comment by mvertens** [comment] 2017-01-30 02:34
The problem is that the runoff grid is being set to r%05 rather than
r%null.

**Closed** 2017-01-30 13:48 UTC
Labels: bug, in progress
