### ISSUE TITLE
Porting CIME to Blue Waters - Error at subprocess.Popen When Calling qsub

### ISSUE THREAD

**Issue by pengbinpeluo** [ESMCI/cime#2612] opened 2018-05-17 23:51 UTC
Hi, 

We are recently porting CIME (together with CTSM) to Blue Waters. But we encountered a problem when running the case.submit script. The subprocess.Popen call in clm5.0/cime/scripts/lib/CIME/utils.py returns nothing in "output," which leads to the following error:

--------------------
...
Check case OK
submit_jobs case.run
job is case.run
Submit job case.run
Submitting job script qsub    -q normal -l walltime=24:00:00 -A fyy case.run
ERROR: Couldn't match jobid_pattern '^(\S+)$' within submit output:
 ''
--------------------

We run the same qsub command out of CIME environment and it actually worked. You can check our test and exploring results through here https://bb.cgd.ucar.edu/porting-cesm-20-blue-waters-error-subprocesspopen-when-calling-qsub

I appreciate any help from the developing team. Thanks!

Bin.

**Comment by jedwards4b** [comment] 2018-05-18 01:59
I think that the jobid_pattern defined in your config_batch.xml is wrong, it should be:

<jobid_pattern>(\d+.bw)$</jobid_pattern>

Add that to the bluewaters section in your config_batch.xml file.

**Comment by pengbinpeluo** [comment] 2018-05-18 16:21
Thanks, Jim.  

We changed the jobid_pattern and it sill doesn't work. The jobid_pattern only matters when the subprocess.Popen returns something. Our problem here is that the output from subprocess.Popen is null in the CIME environment. You can check our detailed description about the system and porting configurations (as well as our testing) here https://bb.cgd.ucar.edu/porting-cesm-20-blue-waters-error-subprocesspopen-when-calling-qsub

Any further suggestion will be highly appreciated!

Bin.

**Comment by jedwards4b** [comment] 2018-05-18 19:18
I was able to get cime standalone tests working on bluefire with the cime tag cime_cesm2_0_rel_02.
Then I tried a clm test and get the following error 
```
err=perl: symbol lookup error: /usr/lib/perl5/vendor_perl/5.10.0/x86_64-linux-thread-multi/auto/XML/LibXML/Common/Common.so: undefined symbol: Perl_Gthr_key_ptr
```
it does not seem to be solved by loading the modules as suggested in the forum:
```
Currently Loaded Modulefiles:
  1) modules/3.2.10.4                      20) CESM-ENV
  2) eswrap/1.3.3-1.020200.1280.0          21) bwpy/0.3.2
  3) craype-interlagos                     22) pgi/17.5.0
  4) craype-network-gemini                 23) cray-libsci/16.11.1
  5) craype/2.5.8                          24) udreg/2.3.2-1.0502.10518.2.17.gem
  6) cray-mpich/7.5.3                      25) ugni/6.0-1.0502.10863.8.28.gem
  7) torque/6.0.4                          26) pmi/5.0.10-1.0000.11050.179.3.gem
  8) moab/9.1.2-sles11                     27) dmapp/7.0.1-1.0502.11080.8.74.gem
  9) java/jdk1.8.0_51                      28) gni-headers/4.0-1.0502.10859.7.8.gem
 10) globus/5.2.5                          29) xpmem/0.1-2.0502.64982.5.3.gem
 11) gsissh/6.2p2                          30) dvs/2.5_0.9.0-1.0502.2188.1.113.gem
 12) xalt/0.7.6.local                      31) alps/5.2.4-2.0502.9774.31.12.gem
 13) scripts                               32) rca/1.0.0-2.0502.60530.1.63.gem
 14) OpenSSL/1.0.2m                        33) atp/2.0.4
 15) cURL/7.59.0                           34) PrgEnv-pgi/5.2.82
 16) git/2.17.0                            35) papi/5.5.1.1
 17) wget/1.19.4                           36) cray-netcdf-hdf5parallel/4.4.1.1
 18) user-paths                            37) cray-parallel-netcdf/1.8.0
 19) perl5-local                           38) cmake/3.1.3
```

**Comment by pengbinpeluo** [comment] 2018-05-18 20:46
Hi Jim, 

Could you reproduce our problem on the Blue Waters? If not, I would be glad to provide more details if needed.

Thanks, 

Bin.

**Comment by jedwards4b** [comment] 2018-05-18 20:50
Now that I have figured out the perl and python environment I am able to run a case closer to the one you are using.   I suspect that the problem is in the cime tag you are using in ctsm and that the current cime tag has solved it.   You can try this in your ctsm source by going to the cime subdirectory and doing
git fetch origin
git checkout cime_cesm2_0_rel_02
and trying your test again.

**Comment by pengbinpeluo** [comment] 2018-05-19 03:43
Thanks, Jim.  Following your suggestion, we have successfully run the model on Blue Waters. 

Just curious, the default configuration for Blue Waters in the CIME seems to be outdated. Is it possible that you and the developing team update the Blue Waters configurations in the future tag?

Thanks again for the help.

Bin.

**Comment by jedwards4b** [comment] 2018-05-19 13:05
@ekluzek Bin is correct that this problem is in the cime tag released with ctsm but not in the cime tag scheduled for the cesm release.   What are your plans for updating cime in ctsm?

**Comment by ekluzek** [comment] 2018-05-21 15:52
We are updating the release-clm5.0 branch with the latest version of cime. That will be done in a few days.

**Comment by pengbinpeluo** [comment] 2018-05-28 03:44
Thanks, @jedwards4b   and @ekluzek 

As shown in our porting test, the default configurations (software package environment) for Blue Waters in config_machines.xml file seems need to be updated if we want to run CTSM. Can the CIME team updated that in case other uses want to run it on Blue Waters?

Bin.

**Comment by jedwards4b** [comment] 2018-05-30 17:27
This is not an issue on the current master or maint-5.6 branch, closing.

**Closed by jedwards4b** 2018-05-30 17:27 UTC
