### ISSUE TITLE
pio strides reset by default in CIME

### ISSUE THREAD

**Issue by jayeshkrishna** [ESMCI/cime#1433] opened 2017-04-27 17:00 UTC
On master (cime5.3.0-alpha.07-144-g8924bb3) case.setup always resets
pio strides/numtasks to defaults (PES_PER_NODE) independent of the current
values in env_run.xml, if I don't specify "--no-adjust-pio". 
The default value of PIO_STRIDE in env_run.xml (after running ./create_newcase,
and before ./case.setup is run) comes from config_pio.xml .
 There are two cases that fail due to ./case.setup adjusting pio strides/numiotasks by
default,
* There is a machine specific setting for stride in config_pio.xml 
* The user manually modifies env_run.xml, to set pio strides to something different
  from PES_PER_NODE, after creating a new case (before ./case.setup is run)

**Comment by jayeshkrishna** [comment] 2017-04-27 17:01
For example, in ACME, we have specific pio_stride for Cetus/Mira that don't work unless the user specifies "--no-adjust-pio" when running ./case.setup.

**Comment by jayeshkrishna** [comment] 2017-04-27 17:02
I think the option for ./case.setup should be "--adjust-pio" (By default the pio strides etc is not adjusted, it is whatever is there in env_run.xml. However user can request it to be adjusted like for some tests where the user knows that the values needs to be readjusted)

**Comment by jayeshkrishna** [comment] 2017-04-27 17:04
The relevant part of the code in discussion is the following function in scripts/lib/CIME/case_setup.py that is always called by default: 
```
def adjust_pio_layout(case, new_pio_stride):

    models = case.get_values("COMP_CLASSES")
    for comp in models:
        pio_stride = case.get_value("PIO_STRIDE_%s"%comp)
        pio_numtasks = case.get_value("PIO_NUMTASKS_%s"%comp)
        ntasks = case.get_value("NTASKS_%s"%comp)
        new_stride = min(ntasks, new_pio_stride)
        new_numtasks = max(1, ntasks//new_stride)
        if pio_stride != new_stride:
            logger.info("Resetting  PIO_STRIDE_%s to %s"%(comp, new_stride))
            case.set_value("PIO_STRIDE_%s"%comp, new_stride)
        if pio_numtasks != new_numtasks:
            logger.info("Resetting  PIO_NUMTASKS_%s to %s"%(comp, new_numtasks))
            case.set_value("PIO_NUMTASKS_%s"%comp, new_numtasks)
```

**Comment by jedwards4b** [comment] 2017-04-27 20:52
I agree that this is a problem - but changing to --adjust-pio  will have issues to.  I know that some of the tests will break unless we change them to add the adjust-pio flag.  But if we add the flag then presumably those tests will have problems on the machines cetus/mira.    How about if we add an optional  DEFAULT_PIO_STRIDE field to config_machines.xml  - if this field is present for a given machine it will be used and the default (if it isn't present) will be TASKS_PER_NODE.

**Comment by jedwards4b** [comment] 2017-04-27 20:53
I will prototype something for your review...

**Comment by jayeshkrishna** [comment] 2017-04-27 21:25
It may be confusing to add another field to config_machines.xml (there are already similar settings in config_pio.xml and that setting could be used instead)
There is still the issue of the user modifying env_run.xml before case.setup is run.
What I think we want to find out is whether the user explicitly set the stride (config_pio.xml or modifying env_run.xml) or not.

**Comment by jayeshkrishna** [comment] 2017-04-28 16:42
I am not sure if adding another machine-specific field is the right approach. We should be able to distinguish between cases where the user explicitly sets the stride (config_pio.xml or modifying env_run.xml) vs cases where CIME is free to choose the value.

**Comment by jedwards4b** [comment] 2017-04-28 16:43
DId you look at or try the PR?   It doesn't add a new machine specific field, only a mechanism to remember and reuse the default value for a given machine.

**Comment by jayeshkrishna** [comment] 2017-04-28 16:48
I haven't tried it yet, just glanced through the changes. I am looking at it now.

**Comment by jayeshkrishna** [comment] 2017-04-28 17:09
So what should I do to get custom pio_strides on Mira (custom pio strides are set in config_pio.xml for Mira)?

**Comment by jedwards4b** [comment] 2017-04-28 17:10
You get them when you create a case.

**Comment by jayeshkrishna** [comment] 2017-04-28 17:16
I tried an X case on Mira and I am still getting "Resetting PIO_STRIDE_* to 4" messages. Where did you test the code (and are there any special args that I need to pass to case_setup)?

**Comment by jedwards4b** [comment] 2017-04-28 17:19
what is happening in an X case is that the default you have in config_pio.xml  (128) is more tasks than you are using for the case.   Resetting to 4 is a last ditch effort to find something that will work at run time.   This  should be okay for an X case.   Now try a case that uses more tasks.

**Comment by jayeshkrishna** [comment] 2017-04-28 17:24
IMO, CIME should not reset strides explicitly set by the user (only reset numiotasks if it is invalid).

**Comment by jedwards4b** [comment] 2017-04-28 17:26
That reset is in the fortran, not in the scripting.
It won't work at all if you are setting PIO_STRIDE to 128 and TOTALTASKS to 64.  Would you prefer it just fail outright?

**Comment by jayeshkrishna** [comment] 2017-04-28 17:28
Hmm, a stride of 128, totaltasks = 64 and a pio_root=0 should result in just 1 io task, right (the stride is not invalid)?

**Comment by jedwards4b** [comment] 2017-04-28 17:30
Can you confirm that the code works as expected when you have enough tasks to start with - I think that this argument about what happens if you request too few tasks is another issue.

**Comment by jayeshkrishna** [comment] 2017-04-28 17:32
And the reset should be happening in the scripts, I just ran create_newcase and case_setup.
Let me try a larger case.

**Comment by jedwards4b** [comment] 2017-04-28 17:35
> I tried an X case on Mira and I am still getting "Resetting PIO_STRIDE_* to 4" messages. Where did you test the code (and are there any special args that I need to pass to case_setup)?

This was a runtime error wasn't it?   I don't think that this was reset in the scripts.   Can you look in the drv_in namelist and confirm the pio_stride value.

**Comment by jayeshkrishna** [comment] 2017-04-28 17:35
"Resetting PIO_STRIDE_* to 4" messages are coming from lib/CIME/case_setup.py

**Comment by jedwards4b** [comment] 2017-04-28 17:36
What is the pelayout for this job?   xmlquery NTASKS NTHRDS ROOTPE

**Comment by jedwards4b** [comment] 2017-04-28 17:39
new_stride = min(ntasks, new_pio_stride)  so resetting to 4 should only happen if ntasks is 4 and should not be a problem.

**Comment by jayeshkrishna** [comment] 2017-04-28 17:39
```
[jayesh@cetuslac1 tmp_X_f19_g16 (jedwards4b-pio_readjust)]$ ./xmlquery NTASKS NTHRDS ROOTPE

Results in group mach_pes
	NTASKS: ['CPL:4', 'ATM:4', 'LND:4', 'ICE:4', 'OCN:4', 'ROF:4', 'GLC:4', 'WAV:4', 'ESP:4']
	NTHRDS: ['CPL:1', 'ATM:1', 'LND:1', 'ICE:1', 'OCN:1', 'ROF:1', 'GLC:1', 'WAV:1', 'ESP:1']
	ROOTPE: ['CPL:0', 'ATM:0', 'LND:0', 'ICE:0', 'OCN:0', 'ROF:0', 'GLC:0', 'WAV:0', 'ESP:0']

```

**Comment by jedwards4b** [comment] 2017-04-28 17:39
So there is nothing wrong with that reset.

**Comment by jedwards4b** [comment] 2017-04-28 17:41
Now in that same case try
xmlchange NTASKS=512
case.setup --reset
./xmlquery PIO_STRIDE

**Comment by jayeshkrishna** [comment] 2017-04-28 17:46
A case with 512/1024 tasks reflects the stride (128) from config_pio.xml .
* create_newcase
* change NTASKS=512
* case_setup (case_setup no longer resets the stride to 4, the stride in env_run.xml is 128)

**Comment by jayeshkrishna** [comment] 2017-04-28 17:52
How about the case where user explicitly sets the stride for each component (different stride for each component) in env_run.xml?
It looks like the code resets all strides to default (On Mira+X+512tasks+128 stride in config_pio & different strides for each component in env_run.xml)

**Comment by jedwards4b** [comment] 2017-04-28 17:53
That is the case that would use the --no-adjust-pio option

**Comment by jayeshkrishna** [comment] 2017-04-28 17:55
I would have preferred an "--adjust-pio" option instead, where the user explicitly tells CIME to adjust the pio layouts. I think the default behaviour should not be resetting the values already in env_run.xml .

**Comment by jedwards4b** [comment] 2017-04-28 18:27
So we need to explain to 90% of our users (who don't customize pio settings) to use this additional option so that the 10% who do make pio adjustments don't need to?

**Comment by rljacob** [comment] 2017-04-28 18:57
The example way at the top:  an OOB setting from config_pio.xml was overwritten by case.setup.  That should never happen.  If OOB settings for PIO are bad, why can't that be fixed in the config files?  Why does case.setup have to correct it?

**Comment by jedwards4b** [comment] 2017-04-28 19:07
@rljacob that example is now fixed

**Comment by jedwards4b** [comment] 2017-04-28 19:08
The issue is that changing the pe-layout may cause the pio settings to become bad and so they need to be readjusted

**Comment by jayeshkrishna** [comment] 2017-04-28 19:22
The 90% of users who don't customize pio settings and adjust the pe layout also probably don't have customized settings for pio (in config_pio.xml, manual modification of env_run.xml) etc. So the code should be modified so that "--adjust-pio" option is not needed (CIME is choosing the stride etc in this case because the user chose not to set it explicitly) if the user leaves the settings as default (no custom settings in config_pio.xml etc)

**Comment by rljacob** [comment] 2017-04-28 19:27
I think what we need is more communication with the user.  If case.setup is going to change the pio settings, it should prompt the user:  "Changing pio settings to match pe layout. OK?" y/n.

Then we can have both --adjust-pio (assume "y") and --no-adjust-pio (assume "n") command line options.

**Comment by gold2718** [comment] 2017-04-28 19:37
I sort of agree with @jayeshkrishna. With no user action, the scripts should set up a default layout that is functional (if not optimal). To this end, I think the default values for `PIO_STRIDE` and `PIO_NUMTASKS` should be `-99`, not `$PES_PER_NODE` and `1` respectively.
If this suggestion is followed, then no switch (`--[no-]adjust-pio`) is needed.
If a user decides to customize their layout, they should be able to do so by setting variables such as `PIO_STRIDE` and `PIO_NUMTASKS`.
If a user decides to revert to letting the scripts decide the layout, they can follow the existing documentation and set those values to `-99`.

**Comment by jedwards4b** [comment] 2017-04-28 19:58
@gold2718 we removed that code from the fortran quite some time ago and determined that it was better handled in the scriipts.

**Comment by gold2718** [comment] 2017-04-28 20:16
@jedwards4b, I didn't say anything about Fotrran, what am I missing? The XML files still say use `-99` to have the value automatically computed. Is this not correct?

**Comment by jedwards4b** [comment] 2017-04-28 20:55
Alright I'll go back to the drawing board on this one...

**Closed** 2017-05-01 15:26 UTC
Labels: bug, in progress, topic:  scripts
