### ISSUE TITLE
":" in test-id name causes error during build

### ISSUE THREAD

**Issue by cacraigucar** [ESMCI/cime#433] opened 2016-08-19 17:47 UTC
When I issue the command:
./create_test --xml-machine yellowstone --xml-compiler intel --xml-category aux_cam --test-id aux_cam_10:58:37

the job attempts to run, but there are misleading errors during compilation.  I would suggest that if the above name is not a valid name, then the error should be trapped and reported as such.  If it is a valid name, then a different fix will need to be made.

According to @gold2718 this behavior is also in the cime4, so it appears to be a bug that was migrated.

**Comment by billsacks** [comment] 2016-08-20 02:22
Is this a duplicate of https://github.com/CESM-Development/cime/issues/334 (but adding ':' to the list of disallowed characters), or is this a different issue (i.e., unrelated to the validity of the case name itself)?

**Comment by cacraigucar** [comment] 2017-04-07 20:38
I tested this again and this error still exists

**Comment by erichlf** [comment] 2017-04-19 17:58
@cacraigucar what was the recent command you tried to use? Trying to use the original command doesn't work due to unknown options it seems.

**Closed** 2017-04-20 16:23 UTC
Labels: in progress
