### ISSUE TITLE
Replace cime cs_status with cimeteststatus

### ISSUE THREAD

**Issue by rljacob** [ESMCI/cime#104] opened 2016-03-18 17:49 UTC

**Comment by rljacob** [comment] 2016-07-08 19:37
@jgfouca I think this task was entered based on something you said?

**Comment by jgfouca** [comment] 2016-07-08 20:02
@rljacob apologies, I don't remember.

**Comment by billsacks** [comment] 2016-08-09 17:20
This seems to basically be a duplicate of #293 so I'm closing it.

**Closed by billsacks** 2016-08-09 17:20 UTC
